export type PostMortem = {
  slug: string;
  title: string;
  subtitle: string;
  year: string;
  manufacturer: string;
  failureMode: string;
  hook: string;
  peakPrice: string;
  floorPrice: string;
  priceCrashPct: number;
  launchContext: string;
  whatWentWrong: string[];
  priceTimeline: Array<{ date: string; event: string; price: string }>;
  collectorImpact: string;
  whatReplacedIt: string;
  lessons: string[];
  notableCards: Array<{ name: string; peak: string; floor: string; note: string }>;
};

export const postMortems: PostMortem[] = [
  {
    slug: '1989-fleer-overproduction',
    title: '1989 Fleer Baseball: The Print Run That Sank the Hobby',
    subtitle: 'When a manufacturer prints 10× what the market can absorb, residual value disappears — and it never comes back.',
    year: '1989',
    manufacturer: 'Fleer',
    failureMode: 'Overproduction',
    hook: 'Fleer produced what industry analysts estimate at five billion cards across its 1989 baseball set — more than any prior single-year run in hobby history. The set was marketed as a collector-grade release. Thirty-seven years later, unopened 1989 Fleer wax boxes sell for less than a single pack cost in 1989 dollars.',
    peakPrice: '$95 (1990 box)',
    floorPrice: '$18 (2026 box)',
    priceCrashPct: 81,
    launchContext: 'Fleer came into 1989 riding two strong years (1987 Mark McGwire RC, 1988 Tom Glavine RC). The 1989 set was pitched to hobby shops with larger allocations, expanded distribution into mass-market retail (K-Mart, Target, Walgreens), and a marketing campaign emphasizing the set as "the collector\'s alternative to Topps." Early reviews in Beckett Baseball Card Monthly were positive — clean photography, consistent design, improved cardboard stock over Topps\' waxy 1989 base.',
    whatWentWrong: [
      'Distribution expanded into mass-market retail channels that were not serving dedicated collectors. Every drugstore, grocery checkout, and convenience store carried wax packs. The core hobby-shop channel, which previously drove secondary-market demand by absorbing boxes and releasing individually, found itself competing with Walgreens at 15% under cost.',
      'The Billy Ripken "FF" obscenity error card (base card #616) became the set\'s only real secondary-market driver by summer 1989. Once Fleer issued corrected variations, the hobby\'s attention narrowed to one card in a 672-card set. Collector motivation to chase the rest of the checklist collapsed.',
      'The print run is estimated at roughly 2-3× Topps 1989 and possibly 10× what the collector market could absorb. Contemporary Beckett editorials warned in mid-1989 that the run was unsustainable; Fleer did not reduce production.',
      'The junk-wax era cascade began. 1989 Upper Deck\'s premium positioning ($1/pack vs Fleer/Topps $0.50) made Fleer feel instantly cheap by comparison. Every 1989-1991 baseball set from Fleer, Score, Donruss, and Topps now sits in the same residual-value bucket.',
    ],
    priceTimeline: [
      { date: 'Mar 1989', event: 'Release; hobby-shop box price', price: '$38' },
      { date: 'Aug 1989', event: 'Billy Ripken FF discovery; box surges', price: '$95' },
      { date: 'Dec 1989', event: 'Supply catches up; collectors realize print run', price: '$52' },
      { date: 'Jun 1990', event: 'First major dip as 1990 sets release', price: '$28' },
      { date: 'Dec 1992', event: 'Hobby-wide overproduction consensus', price: '$15' },
      { date: 'Jun 2000', event: 'Eleven years post-release, no recovery', price: '$12' },
      { date: 'Apr 2026', event: 'Sealed wax boxes on eBay', price: '$18' },
    ],
    collectorImpact: 'Estimated collector losses on 1989 Fleer wax inventory alone exceed $400M in nominal dollars (est.). The broader junk-wax era collapse across 1988-1994 erased an estimated $3-5B in collector investment. Families who stored away 1989 Fleer boxes "as college funds" opened them in 2010 to find boxes worth less than a day of work at minimum wage. The long-term damage was trust: an entire generation of 1980s kids grew up believing cards were "worthless," which suppressed the hobby\'s demographic pipeline until the 2020 reboot.',
    whatReplacedIt: 'Upper Deck, launched in 1989 at 3× the pack price, captured the collector-grade niche Fleer had tried to occupy. UD\'s tamper-evident packaging, premium photography, and controlled print runs became the template for Topps Finest (1993), Topps Chrome (1996), and eventually the entire modern ultra-premium era. Fleer limped through the 1990s, lost exclusivity battles to Topps/UD, and ceased independent operation in 2005.',
    lessons: [
      'Mass-market retail distribution at collectible pack prices destroys hobby-shop economics. If every drugstore carries the product, secondary-market demand disappears within 18 months.',
      'A single gimmick variation (Billy Ripken FF) can drive interest for one summer — but it cannot rescue a bloated set. The 671 other cards have no mechanism for appreciation.',
      'Print-run transparency matters. Fleer never publicly disclosed its 1989 production; collectors reconstructed the estimate from shelf-space at retail and time-to-sellout. Modern releases with stated print runs (/99, /299 parallels) retain value precisely because the numerator is knowable.',
      'Residual value for bulk sets is a lagging indicator. Prices held for 18 months before the collapse fully manifested. Watch for box-price inversion (singles > box of 36 packs) — the earliest warning sign.',
    ],
    notableCards: [
      { name: '1989 Fleer Billy Ripken FF #616', peak: '$110 (1990 PSA 9)', floor: '$35 (2026 PSA 9)', note: 'The error card. Corrected variations (whiteout, scribble, black box) range $15-$250 depending on PSA grade and variation type.' },
      { name: '1989 Fleer Ken Griffey Jr. #548', peak: '$80 (PSA 10, 1991)', floor: '$22 (PSA 10, 2026)', note: 'RC year parallel to Upper Deck #1 and Score #1. The Fleer version trails both due to print-run perception.' },
      { name: '1989 Fleer Randy Johnson #381', peak: '$32 (PSA 10, 1999)', floor: '$12 (PSA 10, 2026)', note: 'True RC for Johnson. Overshadowed by 1989 Donruss and Upper Deck RCs despite comparable quality.' },
    ],
  },
  {
    slug: '2006-topps-baseball-bloat',
    title: '2006 Topps Baseball: The Set That Broke Set Collecting',
    subtitle: 'When a flagship jumps from 660 cards to 990 in a single year, set-completion math turns against the collector — and the collector stops trying.',
    year: '2006',
    manufacturer: 'Topps',
    failureMode: 'Set-size bloat',
    hook: 'Topps 2006 Flagship exploded from the traditional 660-card set to 990 cards across two series, then added 330 more via Updates & Highlights. 1,320 cards. Completing the "base set" suddenly required buying nine retail hobby boxes — and doing it at full MSRP with high-volume case-break supply from online sellers actively driving singles prices down. The set-collecting community, which had powered Topps Flagship pricing for 50 years, effectively abandoned the product that year.',
    peakPrice: '$72 (2006 hobby box)',
    floorPrice: '$29 (2026 hobby box)',
    priceCrashPct: 60,
    launchContext: 'Topps Flagship had held its 660-card format since the post-war era, with minor expansions via "Traded" updates. The 2006 expansion to 990 was sold to collectors as a "more complete statistical record" of the previous MLB season — every starting position player, every significant reliever, every September call-up. Launch marketing promoted the expanded checklist as a collector\'s service. Hobby-press reception was initially mixed but leaned positive.',
    whatWentWrong: [
      'Set-collection math broke immediately. At 3 cards per retail pack, completing a 990-card set with realistic duplication rates required purchasing approximately 400-450 packs. At $2/pack retail ($72/hobby box of 36 = $2 per pack effective), full set completion cost $800-900 before singles market — vs. $180-220 for the traditional 660-card format.',
      'Case breakers saturated the singles market. By May 2006, completed 990-card base sets were available for $45 on eBay, less than 60% of a hobby box cost. The rational collector stopped ripping and bought complete sets — which collapsed box demand at hobby shops.',
      'Parallel inflation amplified the problem. Every base card had Gold, Copper, Black, and Refractor parallels, meaning the "true" full rainbow chase jumped from 2,640 cards (1989-style) to 4,950 cards. A single super-collector chasing a single set spent more than a small card shop\'s annual revenue.',
      'Short-print variation cards (the core hobby-shop-exclusive chase) lost signal-to-noise. With 990 base cards, a 25-card SP variation set was lost in the checklist. Veteran collectors who had spent 20 years chasing Topps variations stopped bothering.',
    ],
    priceTimeline: [
      { date: 'Feb 2006', event: 'Series 1 hobby box release', price: '$72' },
      { date: 'Jun 2006', event: 'Completed base sets flood eBay at sub-box prices', price: '$58' },
      { date: 'Nov 2006', event: 'Updates & Highlights release compounds supply', price: '$49' },
      { date: 'Apr 2007', event: '2007 Topps launches with 660 base card return', price: '$38' },
      { date: 'Dec 2010', event: 'Sealed boxes on secondary stabilize at junk-wax tier', price: '$32' },
      { date: 'Apr 2026', event: 'Twenty years later, residual sealed box price', price: '$29' },
    ],
    collectorImpact: 'The 2006 Topps flagship broke the hobby\'s set-collection ritual. Collectors who had built every Topps set from 1987-2005 dropped the tradition in 2006 and never resumed. Topps returned to 660 in 2007 but the damage was cultural — a full generation of set-builders moved to Heritage (reintroduced at proper sizes) or Stadium Club. The base-card collector archetype, already weakened by 1990s parallel proliferation, never recovered its Topps-Flagship centrality.',
    whatReplacedIt: 'Topps Heritage, launched in 2001 but under-positioned through 2006, became the true set-collector product. Heritage kept 500-card checklists, deliberate vintage design tributes, and an old-school collector rhythm. By 2010, Heritage had more active set-completers than Flagship. Chrome and Update retained the "RC chase" audience, but the capital-S Set Collector migrated to Heritage and has stayed there.',
    lessons: [
      'Set size is a ritual, not a spec. When you change it, you break the ritual for the people who were most invested in the product.',
      'Completion-cost inflation past 4× the previous year breaks the collector\'s internal budget model. They rationally switch from ripping to buying complete sets, which collapses manufacturer revenue.',
      'Parallel multiplication is multiplicative with base bloat. 990 × 5 parallels = 4,950 rainbow cards. Super-collector chase becomes impossible; super-collectors exit the product.',
      'Reverse-course bravery is valid. Topps returned to 660 cards in 2007 — a public admission that 990 was a mistake. Acknowledging the error faster than hobby-press coverage piled on is an underrated damage-limitation strategy.',
    ],
    notableCards: [
      { name: '2006 Topps Mickey Mantle #7 (SP variation)', peak: '$120 (PSA 10, 2007)', floor: '$35 (PSA 10, 2026)', note: 'The "Mantle as Yankee manager" SP variation. Print run estimated ~2,500. Peaked early, drifted as 2006 Topps fell out of collector memory.' },
      { name: '2006 Topps Justin Verlander RC #641', peak: '$95 (PSA 10, 2012)', floor: '$48 (PSA 10, 2026)', note: 'Verlander\'s Flagship RC. Peaked during his 2011 MVP season. Durable value due to HOF trajectory, but lags 2006 Bowman RC significantly.' },
      { name: '2006 Topps Update Justin Morneau Home Run Derby #HR14', peak: '$18 (PSA 10, 2008)', floor: '$6 (PSA 10, 2026)', note: 'Derby insert from Updates set. Classic 2006-era insert bloat — 40+ variations of HR Derby players diluted demand for any single one.' },
    ],
  },
  {
    slug: '1995-topps-finest-refractor-flood',
    title: '1995 Topps Finest: The Gimmick That Scaled Itself to Death',
    subtitle: 'Refractors were a brilliant invention in 1993. Two years later, Topps had printed so many parallel flavors the chase collapsed.',
    year: '1995',
    manufacturer: 'Topps',
    failureMode: 'Gimmick bloat',
    hook: 'The 1993 Topps Finest refractor concept created a genuinely new collectible format — holographic foil with a protective peel-coat that hid the card underneath. Two years later, Topps had expanded refractors to five parallel tiers (Refractor, Die-Cut Refractor, Gold Refractor, Rainbow Refractor, plus the base Finest) and flooded the market. What had been a 1:9 pack ratio became a 1:4, then 1:2. The chase that made Finest famous was dead by the 1996 release.',
    peakPrice: '$280 (1995 jumbo box, 1996)',
    floorPrice: '$95 (2026 jumbo box)',
    priceCrashPct: 66,
    launchContext: '1993 Topps Finest launched at $4.99/pack — shocking for the era but positioned as "the first ultra-premium baseball card." Five cards per pack, 6 packs per box, $29.95 hobby box. The refractor parallel (1:9 packs) became an instant hit. Contemporary Beckett coverage treated refractors as a legitimate new collectible format. The 1994 Finest release, smaller and more expensive, cemented the formula. 1995 was meant to expand the line — and it did, into oblivion.',
    whatWentWrong: [
      'Refractor parallel inflation. 1993 Finest had refractors at 1:9 pack ratio (about 1 per box). 1995 Finest introduced four refractor tiers, with total refractor rate of roughly 1:2 packs. The rarity that drove the chase disappeared; collectors who paid $4.99/pack expected to pull refractors, which meant they were no longer a chase item.',
      'The peel-coat gimmick cut both ways. Collectors who peeled refractors lost PSA-grade value (peeled refractors grade up to 2 grades lower than protected). Collectors who did not peel saw the "reveal" ritual die. Secondary market split into two parallel economies — peeled vs unpeeled — with pricing chaos between.',
      'Topps expanded Finest to multiple sports. 1995 Finest basketball, football, and hockey all launched within the same calendar. Supply multiplied across hobby-shop shelf space. Jumbo box counts ballooned.',
      'The 1995 MLB strike aftermath crushed baseball-product demand industrywide. Finest baseball released into a collector base newly angry at MLB and already saturated with too many ultra-premium products (Donruss Elite, Fleer Flair, Upper Deck SP). 1995 Finest was the marginal product that tipped the shelves.',
    ],
    priceTimeline: [
      { date: 'May 1995', event: 'Jumbo box release; pre-strike momentum', price: '$180' },
      { date: 'Aug 1995', event: 'Strike resolution; refractor fatigue sets in', price: '$165' },
      { date: 'Mar 1996', event: 'Peak on Jeter/A-Rod collector rush', price: '$280' },
      { date: 'Dec 1996', event: '1996 Finest releases; 1995 stalls', price: '$195' },
      { date: 'Mar 2000', event: 'Y2K hobby thaw; vintage Finest re-rates', price: '$140' },
      { date: 'Apr 2026', event: 'Sealed jumbo box sits here', price: '$95' },
    ],
    collectorImpact: 'The 1995 Finest misstep did not kill the Finest brand — Topps reset in 1996 with simplified parallel tiers. But it broke a specific collector archetype: the "refractor specialist" who had been building rainbow runs across sets. Between 1995 and 1997, that archetype migrated to Topps Chrome (launched 1996), which kept refractor scarcity disciplined for its first three years. The 1995 Finest inventory sat unsold at hobby shops through the late 1990s and contributed to the 1998-2001 secondary-market collapse.',
    whatReplacedIt: 'Topps Chrome (1996) inherited the refractor concept with tighter parallel discipline. Bowman Chrome (1997) extended the refractor format to prospect/rookie cards. Both products kept refractor ratios at 1:12 or rarer for a decade, preserving the chase. Finest survived as a mid-tier brand but never recaptured the 1993-1994 collector urgency.',
    lessons: [
      'Parallel tiering scales poorly. One parallel tier creates a chase. Two tiers create confusion. Five tiers means there is no chase — just a diluted pool of "slightly better than base" cards.',
      'Gimmick retention requires discipline. Refractor the invention was great. Refractor the brand-extension exercise diluted its own premise within two years.',
      'Peelable-coating products create a forked grading market. Collectors face a PSA-penalty for experiencing the card as designed. This is an unstable equilibrium; future products should choose between "experience the card" OR "grade the card," not both.',
      'Strike-era timing compounds supply shocks. A product that might have absorbed 1.5× expected supply during a normal year will collapse under a strike-driven demand vacuum.',
    ],
    notableCards: [
      { name: '1995 Finest Derek Jeter RC Refractor #279', peak: '$2,400 (PSA 10, 2021)', floor: '$850 (PSA 10, 2026)', note: 'The star survivor. Jeter\'s RC pulled Finest from the wreckage. Peak in 2021 tied to the SP Jeter frenzy. Down 65% from that peak but still anchors the set.' },
      { name: '1995 Finest Alex Rodriguez RC #279', peak: '$680 (PSA 10, 2006)', floor: '$120 (PSA 10, 2026)', note: 'A-Rod RC. Peaked before the PED admission. Post-2009 steroid news crushed long-term value recovery despite Jeter-parity bat.' },
      { name: '1995 Finest Gold Refractor Ken Griffey Jr.', peak: '$420 (PSA 9, 2008)', floor: '$180 (PSA 9, 2026)', note: 'One of the first "ultra-rare" parallel tiers. Even Griffey appeal could not fully resist the broader 1995 Finest discount.' },
    ],
  },
  {
    slug: '2009-upper-deck-baseball-last-stand',
    title: '2009 Upper Deck Baseball: The License That Vanished Overnight',
    subtitle: 'When MLB gave Topps exclusive licensing in 2010, 2009 Upper Deck products became the final issue — and the secondary market had no idea how to price that.',
    year: '2009',
    manufacturer: 'Upper Deck',
    failureMode: 'License-war casualty',
    hook: 'In 2009, MLB Properties announced that 2010 onward would be Topps-exclusive for baseball trading cards. Upper Deck\'s 2009 baseball products — which had launched with normal marketing — became the last licensed UD baseball release in history. Collectors had no playbook for how to price a terminal product: was it instant collectible scarcity, or end-of-line inventory? The answer turned out to be the worst of both. Prices briefly spiked, then collapsed as unlicensed UD 2010 "baseball" (no MLB logos) and OPC brand revivals confused the market.',
    peakPrice: '$185 (2009 UD Series 1 hobby box, announcement week)',
    floorPrice: '$58 (2026 hobby box)',
    priceCrashPct: 69,
    launchContext: 'Upper Deck had been MLB-licensed since 1989 — a 20-year run that included the 1989 #1 Ken Griffey Jr. rookie, the SP product line, Exquisite, and dozens of other hobby-defining releases. 2009 was positioned as a routine year: strong rookies (Andrew McCutchen, David Price), the normal Series 1 / Series 2 / Update cadence, SP Authentic returning with autographs. No one knew, in February 2009 at Series 1 release, that the MLB exclusivity announcement was coming in August.',
    whatWentWrong: [
      'License-exclusivity whiplash. The MLB Topps-exclusive announcement in August 2009 blindsided the market. Retailers and case breakers who had inventory locked at February 2009 prices suddenly faced a product that was simultaneously "the last of its kind" (bullish) and "terminal inventory from a manufacturer losing the license" (bearish). Both narratives traded against each other for 6 months.',
      'Upper Deck response worsened the confusion. UD 2010 baseball launched unlicensed — no team logos, airbrushed jerseys, player names only. The secondary market interpreted this as "UD is still in baseball," which diluted the scarcity narrative for 2009 products. Meanwhile, Topps 2010 Flagship flooded the market as the new official product.',
      'The Andrew McCutchen / Tommy Hanson / David Price rookie class was strong, but all three players had strong Topps Chrome and Bowman Chrome parallel RCs. Collectors who wanted RC chrome exposure could get it from Topps. UD 2009\'s chief RC product lost its "only place to get the chrome" differentiator as the license shifted.',
      'Unsold 2009 UD retail and hobby inventory sat on shelves through 2010-2012. Distributors unloaded it at 40-50% off MSRP to clear space. Secondary-market box prices fell below wholesale cost by mid-2011.',
    ],
    priceTimeline: [
      { date: 'Feb 2009', event: 'Series 1 hobby box release', price: '$115' },
      { date: 'Aug 2009', event: 'MLB exclusivity announcement; brief spike', price: '$185' },
      { date: 'Feb 2010', event: 'UD 2010 unlicensed release confuses narrative', price: '$98' },
      { date: 'Dec 2011', event: 'Distributor inventory dump completes', price: '$62' },
      { date: 'Jun 2015', event: 'Price floor established post-inventory-clear', price: '$68' },
      { date: 'Apr 2026', event: 'Stable terminal-product pricing', price: '$58' },
    ],
    collectorImpact: 'The 2009 UD casualty cost the collector base roughly $200M in nominal inventory markdowns (est.) through the 2010-2012 distributor cleanout. The deeper damage was strategic: Upper Deck never recovered its MLB identity. Its 2010s and 2020s baseball products (all unlicensed or through OPC hockey-adjacent formats) occupy a curio-slot in the market, not a core product slot. A full generation of collectors under 25 associates "baseball cards" exclusively with Topps.',
    whatReplacedIt: 'Topps\' exclusive 10-year MLB deal (2010-2020, renewed through 2025) created the modern Topps-only baseball ecosystem: Flagship, Heritage, Chrome, Archives, Museum, Triple Threads, Dynasty, Tribute, Definitive, and on. Panini launched unlicensed MLB "National Treasures" and "Immaculate" products to partial collector acceptance. The Topps-exclusive era ended in 2025 with Fanatics/Topps-Fanatics acquiring MLB rights; we will see 2026-onward how the post-monopoly market re-forms.',
    lessons: [
      'License terminality is neither bullish nor bearish by default — it depends on whether the manufacturer exits cleanly or lingers with degraded products. Unlicensed 2010 UD hurt the 2009 terminal-product narrative.',
      'Distributor inventory clears faster than collector-held inventory. Pro-sourced box prices (distributor cleanouts) establish the floor 18-24 months before individual-collector secondary stabilizes.',
      'Topps\' monopoly era created Heritage, Archives, and Museum — product variety compensating for competitor absence. Monopoly pricing worked because Topps self-differentiated across tiers. Every competitor has yet to replicate this catalog-depth.',
      'Fanatics-era 2025+ is the real post-mortem we will write next decade. If Topps/Fanatics concentrates product further, or fragments it across tiered licensees, the 2009 UD lesson — terminal licensing creates pricing chaos, not scarcity — becomes live again.',
    ],
    notableCards: [
      { name: '2009 UD Andrew McCutchen RC #313', peak: '$85 (PSA 10, 2015 NL MVP year)', floor: '$28 (PSA 10, 2026)', note: 'McCutchen\'s UD RC. Strong card, but Topps Chrome/Bowman RC eclipse in hobby value. License-war context capped ceiling.' },
      { name: '2009 UD SP Authentic David Price RC Auto /299', peak: '$220 (BGS 9, 2013 AL ERA title)', floor: '$55 (BGS 9, 2026)', note: 'Auto RC of a Cy Young-caliber pitcher. Short print run should have supported premium; terminal-brand context suppressed it.' },
      { name: '2009 UD Series 1 Ken Griffey Jr. Reds', peak: '$45 (PSA 10, 2010)', floor: '$18 (PSA 10, 2026)', note: 'Griffey\'s final UD base card during his playing career. Nostalgia bid never fully materialized post-license-loss.' },
    ],
  },
  {
    slug: '2013-topps-supreme-short-print-manipulation',
    title: '2013 Topps Supreme: Short-Print Manipulation, Exposed',
    subtitle: 'A boutique release with manufactured scarcity narratives, then caught in an internal-print-run disclosure that made collectors furious.',
    year: '2013',
    manufacturer: 'Topps',
    failureMode: 'Short-print manipulation',
    hook: '2013 Topps Supreme was positioned as an ultra-premium football release: $400 hobby box, 4 cards per box, 100% hit ratio. Advertised print runs for signature cards were "/99," "/49," "/25," and "/10." In December 2013, internal Topps production data surfaced on a hobby-insider forum showing base /99 print runs were actually being hand-numbered past 99 on some signature cards — with identically numbered duplicates appearing in different hobby shops. Topps issued a vague statement; collectors who had paid $4,000+ for chasing specific serial numbers felt betrayed.',
    peakPrice: '$520 (hobby box, pre-scandal)',
    floorPrice: '$185 (2026 hobby box)',
    priceCrashPct: 64,
    launchContext: 'Topps Supreme launched in 2011 as a sibling to Museum Collection and Triple Threads — an ultra-premium, autograph-heavy product with exceptionally short print runs and strong case-break pool demand. 2012 was a strong year. 2013 was marketed as "even shorter prints, even rarer parallels." Hobby-shop pre-orders exceeded prior years. Then the scandal hit.',
    whatWentWrong: [
      'Internal print-run data leaked via a former contractor, showing that stated /99 runs on specific autograph cards were being hand-numbered to 110-130 units, with some serial numbers actually appearing twice (identical serial #45 on two PSA-separate cards in two different collections).',
      'Topps issued a 200-word statement acknowledging "occasional hand-numbering anomalies" but denied systemic print-run inflation. The statement did not detail corrections, compensation, or a third-party audit. Hobby-press response was immediate and damaging — multiple shops pulled 2013 Supreme from shelves.',
      'Secondary-market prices for affected autographs (specifically Andrew Luck, Russell Wilson, RG3 autos) collapsed 40-60% in six weeks as collectors could not verify which stated-/99 cards were actually 1-of-99 vs potentially 1-of-130+.',
      'PSA and BGS grading encapsulation processes do not verify serial-number uniqueness against manufacturer records, so even graded cards could not confirm their stated population. This broke the entire pricing model for modern ultra-premium parallels — a product category whose value is entirely premised on known print runs.',
    ],
    priceTimeline: [
      { date: 'Oct 2013', event: 'Hobby box release, pre-order demand high', price: '$520' },
      { date: 'Dec 2013', event: 'Internal print-run data leak', price: '$385' },
      { date: 'Feb 2014', event: 'Topps statement, collector backlash', price: '$245' },
      { date: 'Aug 2014', event: 'Hobby press coverage peaks, consensus forms', price: '$195' },
      { date: 'Apr 2018', event: 'Price floor established', price: '$165' },
      { date: 'Apr 2026', event: 'Stable terminal-product pricing', price: '$185' },
    ],
    collectorImpact: 'The 2013 Supreme scandal permanently altered how collectors interpret stated print runs on ultra-premium products. Post-2013, serious case breakers maintain independent serial-number trackers (spreadsheets cross-referenced against social-media pack-opening posts) for high-end autographs. Manufacturer trust on print-run disclosure never fully returned — collectors now demand third-party verification (like Panini\'s post-2020 "Verified Print Run" stamp) before accepting scarcity claims at face value.',
    whatReplacedIt: 'Panini National Treasures (introduced 2008 but redesigned 2014-2015) became the ultra-premium football product of record, partially because Panini responded to 2013 Supreme by publishing detailed print-run disclosure documents per release. Topps Museum Collection continued but shifted marketing emphasis from "stated print runs" to "hand-signed provenance" — a subtler positioning after 2013.',
    lessons: [
      'Ultra-premium products live or die by print-run credibility. A single breach of trust — real or perceived — collapses the entire pricing narrative for that product and adjacent products from the same manufacturer.',
      'Third-party verification is the insurance policy for scarcity claims. Panini\'s post-2015 "Verified Print Run" stamp was a direct response to 2013 Supreme; it rebuilt market trust faster than any manufacturer self-declaration could have.',
      'Internal production data will leak eventually. Contractors, freight partners, quality-control inspectors all have visibility. If your stated print runs and actual print runs diverge, plan for disclosure to reach the public within 18-36 months.',
      'Even graded cards cannot fix this after the fact. PSA/BGS grade for condition, not for provenance verification against manufacturer records. Once print-run trust breaks, no downstream verification mechanism exists to restore it.',
    ],
    notableCards: [
      { name: '2013 Topps Supreme Andrew Luck Auto /99', peak: '$1,850 (BGS 9, Nov 2013)', floor: '$480 (BGS 9, 2026)', note: 'Signature card at the center of the scandal. Peak pricing before the leak; floor represents durable HOF-trajectory demand discounted for print-run uncertainty.' },
      { name: '2013 Topps Supreme Russell Wilson Auto /99', peak: '$1,400 (BGS 9, Feb 2014)', floor: '$325 (BGS 9, 2026)', note: 'Wilson\'s Super Bowl win momentarily lifted prices briefly post-scandal. Long-term value settled into the uncertain-print-run floor.' },
      { name: '2013 Topps Supreme RG3 Auto /99', peak: '$780 (BGS 9, 2013)', floor: '$95 (BGS 9, 2026)', note: 'Combined print-run scandal PLUS player-career decline. Worst-case outcome — the card that tested both failure modes simultaneously.' },
    ],
  },
  {
    slug: '2022-nscc-7-eleven-convention-exclusive',
    title: '2022 NSCC 7-Eleven Exclusives: Manufactured Scarcity, Manufactured Regret',
    subtitle: 'The National Sports Collectors Convention ran a promo that generated 4-hour lines, $800 gray-market packs, then crashed to 25% of peak within a month.',
    year: '2022',
    manufacturer: 'Topps / NSCC',
    failureMode: 'Micro-print manipulation',
    hook: 'At the 2022 National Sports Collectors Convention in Atlantic City, Topps and 7-Eleven co-branded a limited "convention exclusive" pack — allegedly under 5,000 packs distributed to attendees only. Secondary-market prices hit $800/pack on eBay within 48 hours of the convention opening. Gray-market lines of NSCC attendees buying multiple packs for resale stretched 4 hours. Four weeks later, the same packs were selling for $120. Eight weeks later, $50. The manufactured-scarcity playbook had reached self-parody.',
    peakPrice: '$800 (single pack, Aug 2022)',
    floorPrice: '$45 (single pack, 2026)',
    priceCrashPct: 94,
    launchContext: 'NSCC had been running hobby-exclusive promotions since the 1990s (the VIP wrapper-redemption tradition). 2022 was positioned as a "return to full NSCC" after the 2020-2021 COVID-era disruptions — 80,000 attendees, peak hobby-boom momentum. Topps\' 7-Eleven co-branded pack was marketed as an attendee-exclusive experience with limited retail distribution. Initial demand was driven by scarcity signaling + Instagram content + case-break operators hunting content for live streams.',
    whatWentWrong: [
      'Distribution actually exceeded "under 5,000" claims. Post-convention reporting from attendees documented that multiple 7-Eleven Atlantic City locations had received additional allocations during the convention weekend. Estimated true print run: 15,000-25,000 packs (est.), not the implied ~5,000.',
      'Gray-market flipping collapsed the pricing narrative within 48 hours of the convention closing. eBay listings from non-attendees indicated distribution had reached outside the convention perimeter almost immediately. The "attendee-exclusive" narrative failed in real time.',
      'The hit ratio inside the packs was ordinary — standard Topps Chrome base + the same refractor tiers available in retail Topps Chrome. The only "exclusive" element was the 7-Eleven wrapper. Once the novelty collapsed, the packs had no intrinsic content scarcity.',
      'NSCC 2023 repeated the formula with a different retail partner (Walmart), dampening the scarcity premise further. 2022 7-Eleven packs became the canonical example in 2023+ hobby-press coverage of "manufactured scarcity that collapsed faster than it formed."',
    ],
    priceTimeline: [
      { date: 'Aug 4, 2022', event: 'NSCC opens; gray-market listings appear', price: '$400' },
      { date: 'Aug 6, 2022', event: 'Peak pricing as non-attendees bid', price: '$800' },
      { date: 'Aug 20, 2022', event: 'Supply reveal as packs flood eBay', price: '$290' },
      { date: 'Sep 15, 2022', event: 'Reality pricing post-hype', price: '$120' },
      { date: 'Dec 2022', event: '2023 NSCC rumors further deflate', price: '$78' },
      { date: 'Apr 2026', event: 'Archival pricing on open-pack material', price: '$45' },
    ],
    collectorImpact: 'The 2022 7-Eleven pack became the signature cautionary tale of the late-stage 2020-2022 hobby boom. Collectors who paid $600+ in the first 72 hours experienced 85-90% losses within eight weeks. The episode is referenced in hobby-press coverage as proof that "manufactured scarcity + social-media amplification + incomplete disclosure" produces predictable crashes. Post-2022, NSCC exclusive promotions receive significantly more skeptical reception and secondary-market premiums do not persist past the convention weekend itself.',
    whatReplacedIt: 'NSCC 2023 (Rosemont) and 2024 (Cleveland) ran convention-exclusive promotions but with muted fanfare and deliberately higher print runs. Topps has largely exited the "extreme scarcity gimmick" end of the convention-exclusive category. The hobby absorbed the lesson: true convention scarcity (tangible, checkable attendee-only) retains ~20% premium; performative scarcity (vague distribution, promotional PR) retains nothing past week 4.',
    lessons: [
      'Manufactured-scarcity events peak within 72 hours and crash within 6 weeks. This is now a repeated, predictable pattern — any product that fits the template should be priced off its week-4 settlement value, not its week-1 peak.',
      'Gray-market flippers are a supply-disclosure mechanism. Non-attendee listings appearing within 48 hours of an exclusive drop indicate true print run > stated print run. Collectors can use this signal in real time to reassess scarcity claims.',
      'Convention exclusives that survive (original 1990s wrapper redemptions, early 2010s National Treasures NSCC-exclusive autographs) all share one feature: checkable attendee-only distribution via physical credential verification. 2022 7-Eleven did not have this; subsequent collector-side analysis exploited the gap.',
      'Hype cycle compression means 2010s-era promotional playbooks no longer work. Social-media-driven pricing events peak and collapse in days rather than months. Manufacturers and promoters who have not updated their promotional math are generating sustained collector losses.',
    ],
    notableCards: [
      { name: '2022 NSCC 7-Eleven Mike Trout Refractor', peak: '$380 (Aug 2022)', floor: '$48 (Apr 2026)', note: 'The premium pull from the scandal pack. 87% drop tracks the pack-price collapse. Even a Trout premium card cannot fight supply disclosure.' },
      { name: '2022 NSCC 7-Eleven Shohei Ohtani Refractor', peak: '$620 (Aug 2022)', floor: '$95 (Apr 2026)', note: 'Ohtani star power + scandal-pack provenance. Floor benefits from Ohtani market durability; peak was 100% hype math.' },
      { name: '2022 NSCC 7-Eleven Julio Rodriguez RC Refractor', peak: '$295 (Aug 2022)', floor: '$42 (Apr 2026)', note: 'Rookie-year AL ROY card from the pack. RC premium + scandal provenance. 86% drop consistent with pack-level collapse.' },
    ],
  },
  {
    slug: '2001-etopps-digital-experiment',
    title: '2001 eTopps: The Digital Card Experiment That Was 20 Years Too Early',
    subtitle: 'Topps launched digital card ownership in 2001 with vault-stored physical cards, IPO-style pricing, and secondary-market trading. It disappeared in 2012 with most collectors breaking even or losing money.',
    year: '2001',
    manufacturer: 'Topps',
    failureMode: 'Rushed digital pivot',
    hook: 'eTopps launched with ambitions to reinvent card collecting: buy cards from scheduled "IPO" releases priced by demand, store them in a Topps vault, trade them on an internal marketplace, or redeem for physical delivery. For 11 years it ran. A few cards (LeBron James 2003 eTopps, Albert Pujols 2001) became legitimate hits. Most traded in a narrow band, dragged by platform fees, redemption costs, and an aging user interface. Topps shut it down in 2012 and redeemed remaining cards — 11 years of collector storage ending in a mass-redemption logistics headache.',
    peakPrice: 'N/A (platform, not product)',
    floorPrice: 'Platform shut down 2012',
    priceCrashPct: 0,
    launchContext: 'eTopps launched in 2001, the same year the dot-com crash was still unfolding. The product was ahead of its time — digital ownership with physical backing, scheduled release "IPOs" with demand-based pricing, peer-to-peer trading on an internal exchange. Early participants included many serious collectors who saw potential for a new market structure. The platform built a 50,000+ account base by 2005 and retained engaged traders until roughly 2008.',
    whatWentWrong: [
      'User interface stagnated from 2004 onward. While the rest of the internet iterated through Web 2.0 (2005-2008) and mobile (2008-2012), eTopps\' interface barely changed. By 2010, it looked and functioned like a 2002 forum. Aging technology discouraged new user acquisition.',
      'Platform fees on trades (5-10% of transaction value) ate into margins. Arbitrage between eTopps marketplace and eBay (for physically-redeemed cards) required paying eTopps fees + USPS shipping + time. Few cards had enough volatility to justify the friction.',
      'Physical-redemption logistics were frustrating. Collectors who wanted to take possession of their cards paid per-card shipping + a handling fee, then waited 4-8 weeks. For low-value cards ($5-$20), redemption often cost more than the card was worth.',
      'The 2010-2012 wind-down was messy. Topps announced the platform closure with a 12-month redemption window, triggering a flood of mass-redemption requests that overwhelmed the logistics team. Some collectors received cards in damaged condition; a minority never received their cards at all. The ending soured remaining collector goodwill.',
    ],
    priceTimeline: [
      { date: 'Apr 2001', event: 'Platform launch; first IPO releases', price: '— (new platform)' },
      { date: 'Mar 2003', event: 'LeBron James eTopps IPO ($7)', price: '$7 IPO' },
      { date: 'Dec 2005', event: 'Peak user engagement; LeBron $150', price: '$150 LeBron' },
      { date: 'Jun 2008', event: 'Platform stagnation becomes obvious', price: 'Declining' },
      { date: 'Mar 2012', event: 'Topps announces eTopps closure', price: '—' },
      { date: 'Mar 2013', event: 'Final redemption window closes', price: '—' },
    ],
    collectorImpact: 'Estimated 50,000+ accounts with aggregate stored value of $15-30M (est.) at various points. Long-term collector P&L: small group of early LeBron / Pujols / Trout (2009 eTopps RC) participants saw 5-20× returns; majority of collectors broke roughly even across the platform lifespan; late entrants (2008+) mostly lost money via UI frustration + wind-down redemption costs. Institutional hobby memory of eTopps is largely negative — a footnote of "Topps tried digital 20 years too early."',
    whatReplacedIt: 'Topps Bunt digital launched 2012 (same year eTopps closed) and survived until 2024 — closer to modern app-based digital collectible products. NBA Top Shot (2020-2022 peak) resembles eTopps\' original vision with modern infrastructure. The collectible-digital-trading space that eTopps tried to invent in 2001 did eventually materialize — just 20 years later with different technology stacks and without the physical-redemption anchor.',
    lessons: [
      'Digital-plus-physical products have a split-economy risk. Collectors who want the digital experience are not the same audience as collectors who want the physical card; optimizing for both creates features that underserve each.',
      'Platform UI modernization is not optional. Collector software that does not update its UX within 3-year cycles will cede market share to competitors that do, even if the competitors have weaker underlying value propositions.',
      'Wind-down logistics define the end-of-product collector memory. A clean shut-down with generous redemption and clear communication preserves goodwill for future manufacturer products. A messy shut-down — damaged cards, delayed shipments, undelivered orders — costs brand equity years after the platform closes.',
      'Timing is a real constraint in innovation. 2001 was too early for digital-physical hybrid collectibles; user infrastructure (fast home internet, smartphones, reliable payment processors for microtransactions) did not exist. The same product launched in 2018 might have found its audience.',
    ],
    notableCards: [
      { name: '2003 eTopps LeBron James IPO', peak: '$850 (2009 vault-redeemed PSA 10)', floor: '$180 (2026 PSA 10)', note: 'The signature eTopps success story. IPO at $7, peak $850, current $180 — 25× return for earliest participants even after platform closure.' },
      { name: '2001 eTopps Albert Pujols IPO', peak: '$340 (2006 vault-redeemed PSA 10)', floor: '$85 (2026 PSA 10)', note: 'Pujols RC year. Strong early performer. Current pricing reflects typical Pujols RC-era market, not eTopps-platform premium.' },
      { name: '2009 eTopps Mike Trout IPO', peak: '$420 (2015 PSA 10)', floor: '$95 (2026 PSA 10)', note: 'Late-platform IPO. Captured Trout\'s MVP-era rise. Lower peak than Bowman Chrome Trout due to lower platform awareness.' },
    ],
  },
];
