'use client';

import { useState } from 'react';

interface Beneficiary {
  name: string;
  relationship: string;
  allocation: number;
  notes: string;
}

interface CollectionItem {
  category: string;
  description: string;
  estimatedValue: number;
  location: string;
}

const CATEGORIES = ['Graded Cards', 'Raw Cards', 'Sealed Products', 'Memorabilia', 'Supplies/Equipment'];
const RELATIONSHIPS = ['Spouse/Partner', 'Child', 'Sibling', 'Parent', 'Friend', 'Charity', 'Other'];

export default function EstatePlannerClient() {
  const [step, setStep] = useState(0);
  const [items, setItems] = useState<CollectionItem[]>([]);
  const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]);
  const [newItem, setNewItem] = useState<CollectionItem>({ category: CATEGORIES[0], description: '', estimatedValue: 0, location: '' });
  const [newBen, setNewBen] = useState<Beneficiary>({ name: '', relationship: RELATIONSHIPS[0], allocation: 100, notes: '' });

  const totalValue = items.reduce((a, i) => a + i.estimatedValue, 0);
  const totalAllocation = beneficiaries.reduce((a, b) => a + b.allocation, 0);

  const taxEstimate = totalValue > 0 ? {
    federal: totalValue > 12920000 ? Math.round((totalValue - 12920000) * 0.40) : 0,
    collectibleGains: Math.round(totalValue * 0.28 * 0.5),
    stateAvg: Math.round(totalValue * 0.05),
  } : null;

  const addItem = () => {
    if (!newItem.description || newItem.estimatedValue <= 0) return;
    setItems([...items, { ...newItem }]);
    setNewItem({ category: CATEGORIES[0], description: '', estimatedValue: 0, location: '' });
  };

  const addBen = () => {
    if (!newBen.name) return;
    setBeneficiaries([...beneficiaries, { ...newBen }]);
    setNewBen({ name: '', relationship: RELATIONSHIPS[0], allocation: 0, notes: '' });
  };

  const generateDocument = () => {
    const lines = [
      '=== CARD COLLECTION ESTATE PLAN ===',
      `Generated: ${new Date().toLocaleDateString()}`,
      '',
      '--- COLLECTION INVENTORY ---',
      ...items.map((it, i) => `${i + 1}. [${it.category}] ${it.description} — $${it.estimatedValue.toLocaleString()} (${it.location || 'Not specified'})`),
      '',
      `Total Estimated Value: $${totalValue.toLocaleString()}`,
      '',
      '--- BENEFICIARIES ---',
      ...beneficiaries.map(b => `• ${b.name} (${b.relationship}) — ${b.allocation}%${b.notes ? ` — Note: ${b.notes}` : ''}`),
      '',
      '--- TAX CONSIDERATIONS ---',
      `Federal estate tax threshold (2025): $12.92M`,
      `Collectibles capital gains rate: 28%`,
      `Estimated collection value: $${totalValue.toLocaleString()}`,
      '',
      '--- HEIR INSTRUCTIONS ---',
      '1. Do NOT clean, wipe, or handle cards without gloves',
      '2. Graded cards (in slabs) should NOT be opened',
      '3. Get a professional appraisal before selling (PSA, Beckett, Heritage Auctions)',
      '4. Sell individually on eBay for maximum value; avoid bulk buyers',
      '5. Contact a collectibles insurance agent for coverage during transition',
      '6. Consider consignment with PWCC, Goldin, or Heritage for high-value items ($500+)',
      '',
      'Generated by CardVault Estate Planner — cardvault-two.vercel.app/tools/estate-planner',
    ];
    return lines.join('\n');
  };

  const steps = ['Inventory', 'Beneficiaries', 'Tax Info', 'Document'];

  return (
    <div>
      {/* Progress Steps */}
      <div className="flex items-center gap-2 mb-8 overflow-x-auto">
        {steps.map((s, i) => (
          <button key={s} onClick={() => setStep(i)} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${step === i ? 'bg-amber-600 text-white' : step > i ? 'bg-green-900/30 text-green-400' : 'bg-gray-800 text-gray-400'}`}>
            <span className="w-5 h-5 rounded-full flex items-center justify-center text-xs border border-current">{step > i ? '✓' : i + 1}</span>
            {s}
          </button>
        ))}
      </div>

      {/* Step 1: Inventory */}
      {step === 0 && (
        <div>
          <h2 className="text-xl font-bold mb-4">Collection Inventory</h2>
          <p className="text-gray-400 text-sm mb-6">Add the major items in your collection. Focus on high-value cards, sealed products, and significant holdings.</p>

          <div className="bg-gray-900 rounded-xl p-5 mb-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-3">
              <select value={newItem.category} onChange={e => setNewItem({ ...newItem, category: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm">
                {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <input type="text" placeholder="Description (e.g., PSA 10 Trout RC)" value={newItem.description} onChange={e => setNewItem({ ...newItem, description: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
              <input type="number" placeholder="Estimated Value ($)" value={newItem.estimatedValue || ''} onChange={e => setNewItem({ ...newItem, estimatedValue: Number(e.target.value) })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
              <input type="text" placeholder="Location (e.g., Safe, Office)" value={newItem.location} onChange={e => setNewItem({ ...newItem, location: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
            </div>
            <button onClick={addItem} className="bg-amber-600 hover:bg-amber-500 px-4 py-2 rounded-lg text-sm font-medium transition-colors">Add Item</button>
          </div>

          {items.length > 0 && (
            <div className="space-y-2 mb-6">
              {items.map((it, i) => (
                <div key={i} className="flex items-center justify-between bg-gray-900/50 rounded-lg px-4 py-3">
                  <div>
                    <span className="text-xs text-amber-400 mr-2">[{it.category}]</span>
                    <span className="text-sm">{it.description}</span>
                    {it.location && <span className="text-xs text-gray-500 ml-2">({it.location})</span>}
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-semibold text-emerald-400">${it.estimatedValue.toLocaleString()}</span>
                    <button onClick={() => setItems(items.filter((_, j) => j !== i))} className="text-red-400 hover:text-red-300 text-xs">Remove</button>
                  </div>
                </div>
              ))}
              <div className="text-right text-sm font-bold mt-3">Total: <span className="text-emerald-400">${totalValue.toLocaleString()}</span></div>
            </div>
          )}

          <button onClick={() => setStep(1)} className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg text-sm font-medium transition-colors">Next: Beneficiaries →</button>
        </div>
      )}

      {/* Step 2: Beneficiaries */}
      {step === 1 && (
        <div>
          <h2 className="text-xl font-bold mb-4">Beneficiaries</h2>
          <p className="text-gray-400 text-sm mb-6">Who should receive your collection? Assign percentage allocations.</p>

          <div className="bg-gray-900 rounded-xl p-5 mb-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-3">
              <input type="text" placeholder="Name" value={newBen.name} onChange={e => setNewBen({ ...newBen, name: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
              <select value={newBen.relationship} onChange={e => setNewBen({ ...newBen, relationship: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm">
                {RELATIONSHIPS.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
              <input type="number" placeholder="Allocation %" value={newBen.allocation || ''} onChange={e => setNewBen({ ...newBen, allocation: Number(e.target.value) })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
              <input type="text" placeholder="Notes (optional)" value={newBen.notes} onChange={e => setNewBen({ ...newBen, notes: e.target.value })} className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm" />
            </div>
            <button onClick={addBen} className="bg-amber-600 hover:bg-amber-500 px-4 py-2 rounded-lg text-sm font-medium transition-colors">Add Beneficiary</button>
          </div>

          {beneficiaries.length > 0 && (
            <div className="space-y-2 mb-4">
              {beneficiaries.map((b, i) => (
                <div key={i} className="flex items-center justify-between bg-gray-900/50 rounded-lg px-4 py-3">
                  <div>
                    <span className="font-medium text-sm">{b.name}</span>
                    <span className="text-xs text-gray-500 ml-2">({b.relationship})</span>
                    {b.notes && <span className="text-xs text-gray-500 ml-2">— {b.notes}</span>}
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-bold text-blue-400">{b.allocation}%</span>
                    <button onClick={() => setBeneficiaries(beneficiaries.filter((_, j) => j !== i))} className="text-red-400 hover:text-red-300 text-xs">Remove</button>
                  </div>
                </div>
              ))}
              <div className={`text-right text-sm font-bold mt-3 ${totalAllocation === 100 ? 'text-green-400' : 'text-yellow-400'}`}>
                Total Allocation: {totalAllocation}%{totalAllocation !== 100 && ' (should be 100%)'}
              </div>
            </div>
          )}

          <div className="flex gap-3">
            <button onClick={() => setStep(0)} className="bg-gray-700 hover:bg-gray-600 px-6 py-2 rounded-lg text-sm font-medium transition-colors">← Back</button>
            <button onClick={() => setStep(2)} className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg text-sm font-medium transition-colors">Next: Tax Info →</button>
          </div>
        </div>
      )}

      {/* Step 3: Tax Info */}
      {step === 2 && (
        <div>
          <h2 className="text-xl font-bold mb-4">Tax Considerations</h2>
          <p className="text-gray-400 text-sm mb-6">Understanding the tax implications of inheriting a card collection.</p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
            <div className="bg-gray-900 rounded-xl p-5">
              <h3 className="font-semibold mb-3 text-amber-400">Federal Estate Tax</h3>
              <p className="text-sm text-gray-400 mb-2">2025 exemption: $12.92M per person</p>
              <p className="text-sm text-gray-400 mb-2">Rate above exemption: 40%</p>
              {taxEstimate && (
                <p className="text-sm">
                  Your estimate: <span className={taxEstimate.federal > 0 ? 'text-red-400 font-bold' : 'text-green-400 font-bold'}>
                    {taxEstimate.federal > 0 ? `$${taxEstimate.federal.toLocaleString()} potential tax` : 'Below threshold — $0 estate tax'}
                  </span>
                </p>
              )}
            </div>
            <div className="bg-gray-900 rounded-xl p-5">
              <h3 className="font-semibold mb-3 text-amber-400">Collectibles Capital Gains</h3>
              <p className="text-sm text-gray-400 mb-2">Collectibles rate: 28% (higher than standard 15-20%)</p>
              <p className="text-sm text-gray-400 mb-2">Heirs get stepped-up basis at fair market value</p>
              <p className="text-sm text-gray-400">Only taxed on gains ABOVE inherited value</p>
            </div>
            <div className="bg-gray-900 rounded-xl p-5">
              <h3 className="font-semibold mb-3 text-amber-400">Insurance During Transition</h3>
              <p className="text-sm text-gray-400 mb-2">Collection should be insured during estate settlement</p>
              <p className="text-sm text-gray-400 mb-2">Specialty providers: CollectInsure, Hugh Wood</p>
              <p className="text-sm text-gray-400">Typical cost: 1-2% of collection value annually</p>
            </div>
            <div className="bg-gray-900 rounded-xl p-5">
              <h3 className="font-semibold mb-3 text-amber-400">Professional Appraisal</h3>
              <p className="text-sm text-gray-400 mb-2">Required for estates over $5,000 in collectibles</p>
              <p className="text-sm text-gray-400 mb-2">PSA, Beckett, Heritage Auctions offer appraisals</p>
              <p className="text-sm text-gray-400">Cost: $100-$500 depending on collection size</p>
            </div>
          </div>

          <div className="bg-yellow-900/20 border border-yellow-800/30 rounded-xl p-4 mb-6">
            <p className="text-yellow-400 text-sm font-medium">Disclaimer</p>
            <p className="text-yellow-400/70 text-xs mt-1">This tool provides general educational information, not legal or tax advice. Consult a qualified estate planning attorney and tax professional for your specific situation.</p>
          </div>

          <div className="flex gap-3">
            <button onClick={() => setStep(1)} className="bg-gray-700 hover:bg-gray-600 px-6 py-2 rounded-lg text-sm font-medium transition-colors">← Back</button>
            <button onClick={() => setStep(3)} className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg text-sm font-medium transition-colors">Generate Document →</button>
          </div>
        </div>
      )}

      {/* Step 4: Generated Document */}
      {step === 3 && (
        <div>
          <h2 className="text-xl font-bold mb-4">Your Estate Plan Document</h2>
          <p className="text-gray-400 text-sm mb-6">Review and copy your collection estate plan. Share it with your attorney or family members.</p>

          <div className="bg-gray-900 rounded-xl p-5 mb-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold text-amber-400">Collection Summary</h3>
              <span className="text-lg font-bold text-emerald-400">${totalValue.toLocaleString()}</span>
            </div>
            <div className="grid grid-cols-3 gap-3 text-center text-sm mb-4">
              <div className="bg-gray-800 rounded-lg p-2"><div className="font-bold">{items.length}</div><div className="text-xs text-gray-500">Items</div></div>
              <div className="bg-gray-800 rounded-lg p-2"><div className="font-bold">{beneficiaries.length}</div><div className="text-xs text-gray-500">Beneficiaries</div></div>
              <div className="bg-gray-800 rounded-lg p-2"><div className="font-bold">{totalAllocation}%</div><div className="text-xs text-gray-500">Allocated</div></div>
            </div>
          </div>

          <div className="bg-gray-950 border border-gray-800 rounded-xl p-5 mb-6">
            <pre className="text-xs text-gray-300 whitespace-pre-wrap font-mono leading-relaxed">{generateDocument()}</pre>
          </div>

          <div className="flex gap-3">
            <button onClick={() => setStep(2)} className="bg-gray-700 hover:bg-gray-600 px-6 py-2 rounded-lg text-sm font-medium transition-colors">← Back</button>
            <button
              onClick={() => {
                navigator.clipboard.writeText(generateDocument());
              }}
              className="bg-amber-600 hover:bg-amber-500 px-6 py-2 rounded-lg text-sm font-medium transition-colors"
            >
              Copy to Clipboard
            </button>
            <button
              onClick={() => {
                const blob = new Blob([generateDocument()], { type: 'text/plain' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'cardvault-estate-plan.txt';
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg text-sm font-medium transition-colors"
            >
              Download .txt
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
