export interface GuideCardLink {
  slug: string;       // sports card slug OR pokemon card id
  type: 'sports' | 'pokemon';
  label: string;      // display name e.g. "1952 Topps Mickey Mantle #311"
  note?: string;      // short context e.g. "PSA 9 ~$30,000"
}

export interface Guide {
  slug: string;
  title: string;
  summary: string;
  category: string;
  readTime: string;
  icon: string;
  gradient: string;
  content: GuideSection[];
  featuredCards?: GuideCardLink[];
}

export interface GuideSection {
  heading: string;
  body: string;
  bullets?: string[];
  callout?: string;
  calloutType?: 'tip' | 'warning' | 'info';
}

export const guides: Guide[] = [
  {
    slug: 'how-to-start-collecting-cards',
    title: 'How to Start Collecting Cards in 2026',
    summary: 'The beginner-to-collector roadmap: what to buy first, where to buy, how to store safely, and how to avoid the traps that cost new collectors money.',
    category: 'Beginner',
    readTime: '8 min',
    icon: '🃏',
    gradient: 'from-emerald-900/40 via-teal-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'The most iconic postwar sports card' },
      { slug: '1989-upper-deck-ken-griffey-jr-1', type: 'sports', label: '1989 Upper Deck Ken Griffey Jr. #1', note: 'Iconic junk wax era rookie' },
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'Basketball\'s most valuable rookie' },
      { slug: 'base1-4', type: 'pokemon', label: 'Base Set Charizard Holo', note: 'Pokémon\'s benchmark card' },
    ],
    content: [
      {
        heading: 'Pick one lane first',
        body: 'New collectors who try to collect everything collect nothing. The hobby has two dominant categories: sports cards and Pokémon TCG. Both are deep, active markets with real price data. Pick one based on your genuine interest — not what YouTube says is hot right now.',
        bullets: [
          'Sports cards: choose one sport, one era (vintage 1950s–80s, junk wax 1985–93, modern 2000s+)',
          'Pokémon TCG: choose one focus — raw singles, sealed packs, vintage Base Set, or modern Scarlet & Violet',
          'Set a hard monthly budget and stick to it for 6 months before expanding',
        ],
      },
      {
        heading: 'Where to buy (and where not to)',
        body: 'Every channel has trade-offs on price, authenticity risk, and selection.',
        bullets: [
          'eBay sold listings: the best real-world price reference. Always check "Sold" not "Active" listings.',
          'TCGPlayer: best for Pokémon singles. Buyer protection, seller ratings, no negotiation needed.',
          'COMC / Sportlots: good for vintage sports cards, searchable large inventories.',
          'Local card shows: best prices on raw cards, no shipping risk, can inspect in person.',
          'Retail (Target/Walmart packs): worst expected value. Entertainment only — not investment.',
        ],
        callout: 'Never buy graded cards from Facebook Marketplace or local social groups without verifying the case authenticity on PSA\'s website first. Fake slabs are common.',
        calloutType: 'warning',
      },
      {
        heading: 'Storage is not optional',
        body: 'Cards lose value fast from preventable damage. Every card you intend to keep should be protected immediately.',
        bullets: [
          'Penny sleeves first, then a top loader — the standard protective stack for individual cards',
          'Binder storage: use side-loading 9-pocket pages, never top-loading (cards can fall)',
          'Climate matters: avoid attics, basements, garages — humidity and temperature extremes crack cases and warp cards',
          'High-value raw cards ($100+): store in one-touch magnetic cases, flat and dry',
        ],
      },
      {
        heading: 'Understanding what drives value',
        body: 'Card value is driven by four factors, roughly in order of importance: player/character popularity, condition/grade, scarcity (print run or population report), and market timing. Most collectors overweight timing and underweight condition — which is the opposite of what makes money.',
        callout: 'Tip: The PSA Pop Report shows exactly how many cards have been graded at each grade level. Low populations in high grades = genuine scarcity. High PSA 10 populations = grade premium may be lower.',
        calloutType: 'tip',
      },
      {
        heading: 'Avoid the common traps',
        body: 'Most expensive beginner mistakes are avoidable.',
        bullets: [
          'Do not buy sealed wax as an investment — expected value is almost always negative vs. buying singles',
          'Do not pay "book value" — Beckett book values are not market prices. Use eBay sold comps.',
          'Do not grade cards worth less than $100 raw — grading fees (PSA Economy: $25) plus turnaround make economics impossible',
          'Do not buy raw vintage for big money without third-party authentication — alterations and forgeries exist',
        ],
      },
    ],
  },
  {
    slug: 'when-to-grade-your-cards',
    title: 'When to Grade (And When Not To)',
    summary: 'Grading is not always worth it. This guide explains grade economics, which cards benefit most, and how to calculate your actual break-even before submitting.',
    category: 'Grading',
    readTime: '6 min',
    icon: '🏅',
    gradient: 'from-blue-900/40 via-indigo-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '2009-bowman-chrome-mike-trout-bdpp89', type: 'sports', label: '2009 Bowman Chrome Mike Trout', note: 'PSA 10 commands massive premium over PSA 9' },
      { slug: '2003-04-topps-chrome-lebron-james-111', type: 'sports', label: '2003-04 Topps Chrome LeBron James #111', note: 'High PSA 10 population affects premium' },
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'Vintage where grading is almost always worth it' },
      { slug: 'base1-4', type: 'pokemon', label: 'Base Set Charizard Holo', note: 'PSA 10 Shadowless: one of the rarest grades in the hobby' },
    ],
    content: [
      {
        heading: 'The break-even math',
        body: 'Grading only makes financial sense when the expected grade premium exceeds your all-in cost. Your all-in cost includes: submission fee, two-way shipping (~$20–35 round trip), insurance if required, and your time.',
        bullets: [
          'PSA Economy ($25) + shipping ($30) = ~$55 minimum. Card needs $55+ value increase to break even.',
          'PSA Express ($150) + shipping = ~$185 minimum. Only for cards where a grade jump adds $500+.',
          'BGS Standard ($35) + shipping = ~$65 minimum. Better for cards where Black Label 9.5 commands a large premium.',
        ],
        callout: 'Rule of thumb: If a PSA 9 version of your card sells for less than 3× your PSA 7/8 raw price, grading is not worth it financially.',
        calloutType: 'tip',
      },
      {
        heading: 'Cards that grade well vs. cards that do not',
        body: 'Not all cards are worth submitting regardless of economics.',
        bullets: [
          'Vintage (pre-1980): Grade even lower-grade copies for authenticity. Collectors pay a meaningful premium for slabbed vintage over raw.',
          'Modern star rookies (post-2000): Only grade if condition is near-perfect. The difference between PSA 8 and PSA 9 is often 2–5×.',
          'Common modern cards: Almost never worth grading — high PSA 10 populations make the grade premium small.',
          'Pokémon vintage (Base Set, Jungle, Fossil): High demand for high-grade slabs. Check pop report first.',
          'Modern Pokémon (Scarlet & Violet era): Only Special Art Rares and Illustration Rares typically support grade premiums.',
        ],
      },
      {
        heading: 'Choosing the right grading company',
        body: 'PSA is the market standard for maximum liquidity. BGS is preferred by some collectors for subgrade transparency and Black Label prestige. SGC is growing for vintage baseball. Choose based on what buyers for your specific card prefer.',
        bullets: [
          'PSA: highest name recognition, most liquidity, largest pop report database',
          'BGS: subgrades tell you exactly why a card scored what it did; Black Label 10 is genuinely rare',
          'SGC: faster for vintage, growing collector base, slightly lower premiums than PSA',
          'CGC (comic company): limited market acceptance for cards — avoid for most sports and Pokémon',
        ],
      },
      {
        heading: 'How to evaluate condition before submitting',
        body: 'Submitting cards in less-than-optimal condition wastes money. Check these before sending:',
        bullets: [
          'Corners: use a loupe (jeweler\'s magnifier) — PSA 10 allows zero corner wear',
          'Centering: measure with a ruler or centering tool — PSA 10 requires 55/45 or better on all sides',
          'Surface: check for print lines, scratches, haze under bright light at an angle',
          'Edges: run a fingertip along edges — any roughness reduces grade',
        ],
        callout: 'If a card would not grade PSA 9 or better, the economics rarely justify Economy submission. Grade only what you believe will come back 9 or 10.',
        calloutType: 'warning',
      },
    ],
  },
  {
    slug: 'how-to-read-price-data',
    title: 'How to Read Card Price Data',
    summary: 'Book values, market prices, sold comps — they all mean different things. This guide explains what each metric is, which to trust, and how to use them to make decisions.',
    category: 'Pricing',
    readTime: '5 min',
    icon: '📊',
    gradient: 'from-amber-900/40 via-orange-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '2000-playoff-contenders-tom-brady-144', type: 'sports', label: '2000 Playoff Contenders Tom Brady #144', note: 'Example: PSA 10 sold $3.1M at auction' },
      { slug: '2003-04-topps-chrome-lebron-james-111', type: 'sports', label: '2003-04 Topps Chrome LeBron James #111', note: 'Active market with daily sold comps' },
      { slug: '2018-topps-chrome-shohei-ohtani-150', type: 'sports', label: '2018 Topps Chrome Shohei Ohtani #150', note: 'High volume — easy to find recent comps' },
    ],
    content: [
      {
        heading: 'The three price sources (and what they actually mean)',
        body: 'Most pricing confusion comes from mixing up three fundamentally different data types.',
        bullets: [
          'Beckett Book Value: a subjective editorial price set by Beckett staff. Outdated quickly. NOT market price. Used primarily as a reference anchor by hobby veterans who grew up with it.',
          'TCGPlayer Market Price: the trailing average of actual sales on TCGPlayer for Pokémon singles. Real data, ~24hr lag. The best single price reference for modern Pokémon.',
          'eBay Sold Comps: the ground truth. Real transactions, searchable by exact card and grade. Most reliable for sports cards, vintage Pokémon, and graded copies.',
        ],
        callout: 'When someone says "it books for $X" — that\'s Beckett. When someone says "it sold for $X" — that\'s real. These numbers can differ by 50–300% for popular cards.',
        calloutType: 'warning',
      },
      {
        heading: 'How to pull an eBay sold comp',
        body: 'Finding accurate comps takes one minute:',
        bullets: [
          '1. Go to eBay. Search the exact card: "[Year] [Player] [Set] [Card Number] [Grade if graded]"',
          '2. On the left sidebar: check "Sold Items" under "Show Only"',
          '3. Sort by: "Ending soonest" first (most recent), then expand to 90 days if too few results',
          '4. Filter by: condition (graded vs raw), specific grade (PSA 9, PSA 10, etc.)',
          '5. Look for the median of recent sales — ignore outliers on both ends',
        ],
      },
      {
        heading: 'Grade multipliers',
        body: 'The same card in different grades can sell for wildly different amounts. These are general ranges — individual cards vary significantly.',
        bullets: [
          'PSA 10 vs PSA 9: typically 3–15× higher. Higher for vintage or low-pop cards.',
          'PSA 9 vs PSA 8: typically 2–4× higher. This is often the biggest value jump.',
          'PSA 8 vs PSA 7: typically 1.5–2× higher.',
          'Raw NM vs PSA 8: raw typically 40–60% of PSA 8 price (varies by card liquidity).',
        ],
        callout: 'Use our Grade Value Calculator to estimate the value across all grade tiers from a single known price.',
        calloutType: 'tip',
      },
      {
        heading: 'When prices are misleading',
        body: 'Not all sales data is good data.',
        bullets: [
          'Single anomalous eBay sales: one record sale does not reset the market. Look at 5–10 sales.',
          'Active listings: asking prices mean nothing — sellers list high, buyers decide the actual market.',
          'Low-volume vintage: if fewer than 5 cards have sold in 90 days, pricing is illiquid. Any sale can be an outlier.',
          'Auction house prices: Heritage, Goldin, and PWCC sales often exceed market due to auction premium and premium buyer pool. Adjust down ~10–20% for actual comparable market.',
        ],
      },
    ],
  },
  {
    slug: 'sports-card-eras-explained',
    title: 'Sports Card Eras: Vintage, Junk Wax & Modern',
    summary: 'The hobby\'s history in plain language. What made each era different, which cards matter from each period, and what it means for today\'s market.',
    category: 'History',
    readTime: '7 min',
    icon: '📅',
    gradient: 'from-red-900/40 via-rose-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1909-11-t206-ty-cobb-portrait-red', type: 'sports', label: '1909-11 T206 Ty Cobb', note: 'Pre-War era benchmark' },
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'Golden Age centerpiece' },
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'Junk Wax era exception' },
      { slug: '1989-upper-deck-ken-griffey-jr-1', type: 'sports', label: '1989 Upper Deck Ken Griffey Jr. #1', note: 'Defining rookie of the junk wax era' },
      { slug: '1993-sp-derek-jeter-279', type: 'sports', label: '1993 SP Derek Jeter #279', note: 'Key exception in a worthless era' },
      { slug: '2009-bowman-chrome-mike-trout-bdpp89', type: 'sports', label: '2009 Bowman Chrome Mike Trout', note: 'Modern era defining rookie' },
    ],
    content: [
      {
        heading: 'The Pre-War Era (before 1941)',
        body: 'The earliest collectible cards, predating organized baseball\'s modern era. T206 tobacco cards (1909–1911) are the most iconic — issued inside cigarette packs, featuring hundreds of players. The T206 Honus Wagner is the most famous and valuable sports card ever made.',
        bullets: [
          'Key sets: T206 (1909–11), T205, E90-1 American Caramel, 1914 Cracker Jack',
          'Condition: extremely rare in top grades due to age and handling over 100+ years',
          'Market: illiquid but stable. Prices driven by historical significance and extreme rarity.',
          'Who collects it: museum-level collectors and deep-pocketed hobbyists. Not a beginner market.',
        ],
      },
      {
        heading: 'The Golden Age (1948–1979)',
        body: 'The Bowman and Topps era. Modern-format cards with real photography, produced in sets. This era contains most of baseball\'s golden age players — Mantle, Mays, Aaron, Clemente. The 1952 Topps set is the most iconic of the era.',
        bullets: [
          'Key cards: 1952 Topps Mickey Mantle #311, 1955 Topps Roberto Clemente, 1963 Topps Pete Rose rookie',
          'Condition: PSA 8+ copies are rare and valuable; most copies grade PSA 4–6',
          'Market: strong and active. Significant grading population supports reliable comps.',
          'Who collects it: core of the "investment-grade" hobby. Price stability vs. modern volatility.',
        ],
      },
      {
        heading: 'The Junk Wax Era (1985–1993)',
        body: 'The most overproduced era in hobby history. Card companies printed billions of cards in response to collector demand, creating a glut that still suppresses prices today. Most junk wax cards are worth cents regardless of grade — with notable exceptions.',
        bullets: [
          'Why most are worthless: print runs in the hundreds of millions, massive surviving supply',
          'Notable exceptions: 1986 Fleer Michael Jordan (limited production), 1989 Upper Deck Ken Griffey Jr. rookie, 1993 SP Derek Jeter',
          'PSA 10 premiums: even junk wax has PSA 10 premium due to poor centering from era — a Griffey PSA 10 vs PSA 9 gap is often 10×',
          'Beginner trap: most card show bins are full of 1988–1992 cards with zero value. Know before you buy.',
        ],
        callout: 'A common beginner mistake: seeing a "1989 Rickey Henderson Topps" and thinking it\'s valuable because Henderson is a Hall of Famer. Topps printed 3 billion+ cards in 1989. It\'s worth a quarter.',
        calloutType: 'warning',
      },
      {
        heading: 'The Modern Era (2000–present)',
        body: 'Defined by serial-numbered parallels, autographs, patch cards, and premium brands. The market bifurcated: massive print runs for base cards (nearly worthless) and ultra-short-print premium cards that command serious money.',
        bullets: [
          'Key innovation: /10, /25, /50 serial-numbered parallels — verifiable scarcity printed into the card',
          'Key brands: Topps Chrome, Panini Prizm, National Treasures, Exquisite Collection',
          'Key rookies: 2003 Topps Chrome LeBron, 2009 Bowman Chrome Trout, 2021-22 Prizm Wembanyama',
          'Grading focus: PSA 10 is achievable on modern cards (better manufacturing); pop reports matter for pricing',
        ],
      },
    ],
  },
  {
    slug: 'grading-guide',
    title: 'PSA vs BGS vs SGC: The Complete Grading Company Guide',
    summary: 'Which grading company is right for your card? This guide covers costs, turnaround times, grading standards, and the real-world premium each company commands on the secondary market.',
    category: 'Grading',
    readTime: '10 min',
    icon: '🏅',
    featuredCards: [
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'PSA is the only grading company for this card' },
      { slug: '2003-04-topps-chrome-lebron-james-111', type: 'sports', label: '2003-04 Topps Chrome LeBron James #111', note: 'BGS 9.5 commands significant premium' },
      { slug: '1996-97-topps-chrome-kobe-bryant-138', type: 'sports', label: '1996-97 Topps Chrome Kobe Bryant #138', note: 'Vintage modern where PSA dominates' },
      { slug: '1909-11-t206-ty-cobb-portrait-red', type: 'sports', label: '1909-11 T206 Ty Cobb', note: 'SGC a credible option for pre-war tobacco cards' },
    ],
    gradient: 'from-blue-900/40 via-indigo-900/20 to-gray-900/40',
    content: [
      {
        heading: 'Why the grading company matters as much as the grade',
        body: 'Two cards graded 9 by different companies can sell for dramatically different prices. PSA, BGS, and SGC each have distinct reputations, liquidity profiles, and collector bases. Choosing the wrong company for a specific card can cost you 20–40% at resale. Understanding the differences is not optional knowledge — it is core to operating in the hobby.',
        bullets: [
          'PSA: Professional Sports Authenticators. Founded 1991. Market leader by volume and name recognition.',
          'BGS: Beckett Grading Services. Founded 2001. Known for subgrades and the Black Label 9.5.',
          'SGC: Sportscard Guaranty Corporation. Founded 1998. Strong in vintage baseball and tobacco cards.',
          'CGC Cards: Comic Guaranty Company\'s card division. Growing but still limited market acceptance for most cards.',
        ],
      },
      {
        heading: 'PSA: The standard for maximum liquidity',
        body: 'PSA grades more cards than any other company and commands the highest resale liquidity across most card categories. The PSA slab design has been largely unchanged for decades — familiar to every collector. The PSA 10 is the most recognized designation in the hobby. Population reports are publicly searchable at psacard.com/pop.',
        bullets: [
          'Grading scale: 1 (Poor) to 10 (Gem Mint). Half-point grades (1.5, 2.5, etc.) exist for specific edge cases.',
          'Economy tier: ~$25 per card (most cards, 6-month turnaround in current backlogs)',
          'Collectors Club: $149/year membership, faster turnaround on most service tiers',
          'Express: $150/card for ~15 day turnaround. Only justified for high-value cards.',
          'Super Express: $600/card for 3-day turnaround. Walk-in available at National.',
          'Specialties: vintage research, autograph authentication (PSA/DNA separate service)',
        ],
        callout: 'PSA is the best choice for: vintage cards, any card where you prioritize resale liquidity, and submissions to the National Sports Collectors Convention (NSCC) where walk-in grading is fastest.',
        calloutType: 'tip',
      },
      {
        heading: 'BGS: The subgrade specialists with a premium ceiling',
        body: 'Beckett Grading Services grades four subcomponents independently: Centering, Corners, Edges, and Surface. The overall grade is not always the average — the lowest subgrade creates a floor. This transparency cuts both ways: collectors know exactly why a card received a certain grade, but a single 8.5 subgrade blocks a 9.5 overall.',
        bullets: [
          'BGS 9.5 "Black Label": all four subgrades at 10. The hardest grade in the hobby to achieve.',
          'BGS 10 Pristine: technically reserved for modern cards; all subgrades at 10 and confirmed flawless surface.',
          'BGS 9.5 vs PSA 10: on modern Prizm rookies, a BGS 9.5 often commands 2–5× a PSA 10 due to perceived difficulty.',
          'BGS 9 vs PSA 9: BGS 9 is often considered equivalent or slightly superior, but PSA 9 tends to be more liquid.',
          'Standard tier: ~$35–$50 per card depending on service level',
          'Vintage cards: BGS is less preferred than PSA for pre-1970 cards — PSA dominates that market.',
        ],
        callout: 'BGS is the best choice for: modern parallels and Prizm rookies where you think a BGS 9.5 is achievable, autograph cards where Beckett Authentication (BAS) adds value, and any card where you plan to keep it long-term and subgrade data matters to you.',
        calloutType: 'tip',
      },
      {
        heading: 'SGC: The vintage specialist with growing momentum',
        body: 'SGC has repositioned itself as a premium vintage brand with a distinctive black inner label that many collectors find visually appealing. SGC grades are increasingly accepted in vintage auctions, and the company has won several major auction consignments. Turnaround times are generally faster than PSA at comparable price points.',
        bullets: [
          'SGC 9.5: introduced to compete with BGS 9.5 — growing but still less liquid than PSA 10 for most cards',
          'Vintage focus: pre-1970 baseball, tobacco cards, pre-war — SGC is a respected option',
          'Turnaround: economy tier often 60–90 days vs PSA\'s 120–180 days at comparable price',
          'Standard tier: ~$20–$35 per card at economy level',
          'Growing auction presence: Heritage, Goldin, and PWCC increasingly accept SGC consignments',
          'Pokémon: SGC has growing but still limited acceptance in the Pokémon market vs PSA',
        ],
      },
      {
        heading: 'The grade premium math: what the data shows',
        body: 'Understanding grade premiums helps determine which company to use. These are real-world observations from recent sales, not theoretical — the market sets these premiums.',
        bullets: [
          'Vintage baseball (pre-1970): PSA 8 and 9 copies sell at 2–5× premium over SGC equivalents. PSA dominance is absolute.',
          'Modern basketball rookies (2003–2020): PSA 10 and BGS 9.5 sell at comparable prices; PSA 10 more liquid.',
          'Modern Prizm parallels (2018+): BGS 9.5 can command 3–5× a PSA 10 for the same card.',
          'Hockey (Young Guns): PSA is overwhelmingly preferred. SGC growing slowly.',
          'Pokémon vintage: PSA 9 and 10 dominate. BGS 9.5 increasingly accepted for Base Set holos.',
          'Pokémon modern: PSA 10 is the default benchmark. BGS has minimal market share in modern sets.',
        ],
        callout: 'Quick decision rule: If you are submitting modern Prizm basketball parallels and you genuinely believe the card grades 9.5 on all four BGS subgrades — submit to BGS. Every other case defaults to PSA unless you have a specific reason.',
        calloutType: 'tip',
      },
      {
        heading: 'Submission workflow: avoid the expensive mistakes',
        body: 'The logistics of submitting correctly are where most money is wasted. These are the most common submission errors.',
        bullets: [
          'Never submit cards without double-checking centering first. Off-center cards are the most common grade kill.',
          'Use the appropriate service tier. Economy on a $10,000 card is not saving money — it is 6+ months of illiquidity.',
          'Ship registered mail with tracking. The grading company is not liable for shipping losses.',
          'Photograph every card before submission. Document condition for insurance and comparison.',
          'List cards accurately in the submission — graders may reject or re-assign if metadata is wrong.',
          'Verify authenticity of vintage cards before submitting — PSA screens for alterations and rejects trimmed cards.',
        ],
        callout: 'A trimmed card (corners or edges cut to improve appearance) will be called out and returned ungraded — "authentic, altered." This permanently affects value. If buying expensive raw vintage, get expert eyes on it first.',
        calloutType: 'warning',
      },
      {
        heading: 'The resale reality: what buyers actually pay',
        body: 'Ultimately, the grading company decision is a market decision. Buyers set the premium, not collectors. Study the sold comps on eBay for your specific card across companies before submitting.',
        bullets: [
          'Search: "[card name] PSA 10 sold" and "[card name] BGS 9.5 sold" and compare',
          'Volume matters: if only 3 BGS 9.5 examples have sold in 12 months, that\'s an illiquid market',
          'The "best company" for resale is the one buyers prefer for your specific card — not the one with the highest overall reputation',
          'Time horizon: if you are holding 5+ years, the premium spread between PSA and BGS on modern cards may equalize as the market matures',
        ],
      },
    ],
  },
  {
    slug: 'investing-101',
    title: 'Sports Card Investing 101: What Actually Works',
    summary: 'Sports cards are a speculative asset class, not a guaranteed investment. This guide covers the fundamentals that hold up across market cycles: what drives value, how to think about liquidity, and the mistakes that cost collectors money.',
    category: 'Investing',
    readTime: '12 min',
    icon: '📈',
    gradient: 'from-emerald-900/40 via-teal-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'The canonical investing thesis card — PSA 8 in 2015: ~$5K; 2020 peak: $40K+' },
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'Iconic vintage — durable scarcity premium' },
      { slug: '2009-bowman-chrome-mike-trout-bdpp89', type: 'sports', label: '2009 Bowman Chrome Mike Trout', note: 'Best modern buy-and-hold example' },
      { slug: '1996-97-topps-chrome-kobe-bryant-138', type: 'sports', label: '1996-97 Topps Chrome Kobe Bryant #138', note: 'Retirement + death premium pattern' },
      { slug: '2000-playoff-contenders-tom-brady-144', type: 'sports', label: '2000 Playoff Contenders Tom Brady Auto #144', note: 'Championship-driven appreciation pattern' },
    ],
    content: [
      {
        heading: 'Cards are a speculative asset, not an investment account',
        body: 'The first honest thing to say about sports card investing: it is not a reliable wealth-building strategy. Cards are illiquid assets with high transaction costs, no yield, unpredictable demand cycles, and heavy exposure to individual athlete performance and off-field behavior. Sophisticated collectors treat the hobby as a passion with upside — not as a primary financial vehicle. With that framing established, the market does produce real returns for collectors who understand it.',
        callout: 'The 2020–2021 card market bubble was a generational event, not the baseline. Cards that sold for 10× pre-COVID prices in 2021 often corrected 40–70% by 2023. Understanding cycles is part of the job.',
        calloutType: 'warning',
      },
      {
        heading: 'The four drivers of card value',
        body: 'Card prices are determined by four overlapping factors. Experienced collectors learn to weight them correctly for each card type.',
        bullets: [
          '1. Player demand: the most important driver, and the hardest to predict. Career milestones, Hall of Fame induction, championship wins, and off-field events all move prices. A player\'s death often creates a spike. Retirement often creates a sustained lift.',
          '2. Condition and grade: determines where your card sits within the value spectrum for that player. A PSA 10 vs PSA 8 can be a 5–15× difference on the same card.',
          '3. Scarcity: print run (serial-numbered cards, low-pop vintage) and PSA population report for graded copies. Real scarcity commands sustained premium. Perceived scarcity fades when population grows.',
          '4. Market timing and sentiment: the least important for long-term holds, the most important for short-term flips. Selling at peak sentiment is extremely difficult to time consistently.',
        ],
      },
      {
        heading: 'The buy thesis that holds across cycles',
        body: 'Across three decades of modern sports card data, one thesis has held more consistently than any other: buy iconic rookie cards of players destined for the Hall of Fame while they are active, hold through career milestones, sell on the news or peak sentiment. This is not a guaranteed formula, but it has the best historical base rate.',
        bullets: [
          'Iconic rookie card: the card the market designates as the player\'s definitive rookie. For LeBron it\'s Topps Chrome. For Brady it\'s Playoff Contenders Auto. For Trout it\'s Bowman Chrome.',
          'Hall-of-Fame certainty matters: buying a player 10 years into their career with a clear Hall trajectory gives you a long runway. Buying speculative rookies is a different (higher risk) game.',
          'Milestone events: first championship, 500 HR club, career touchdown record, MVP seasons — all create sustained buying interest. Being positioned before the milestone is the goal.',
          'Condition premium: a PSA 9 of the iconic rookie typically outperforms a PSA 10 of a secondary card for the same player.',
        ],
        callout: 'The 1986-87 Fleer Michael Jordan is the canonical example. Collectors who bought PSA 8 copies in 2015 for ~$5,000 and held through The Last Dance peak in 2020 saw 5–8× returns. The thesis worked: iconic card, clear Hall trajectory, major sentiment catalyst.',
        calloutType: 'tip',
      },
      {
        heading: 'Liquidity: the variable most collectors underestimate',
        body: 'A card is only worth its market price if you can actually sell it. Liquidity — the speed and ease of converting a card to cash — varies enormously across the market and directly affects true realized return.',
        bullets: [
          'Highest liquidity: PSA 10 copies of top rookies (Jordan, LeBron, Griffey, Brady, Trout). Can sell in hours on eBay.',
          'Moderate liquidity: PSA 8–9 copies of top rookies, PSA 10 of secondary stars.',
          'Low liquidity: Numbered parallels (/10 and below), BGS subgrades, multi-card lots, obscure vintage.',
          'Illiquid: Regional parallels, short-printed variations of less popular players, raw graded cards with authentication disputes.',
          'Transaction costs: eBay takes ~13% (seller fees + PayPal). PWCC, Goldin, and Heritage take 10–20% buyer\'s premium. Factor this into any resale math.',
        ],
        callout: 'A card that sells for $10,000 at auction — after 15% buyer\'s premium paid by the buyer, 10% seller fee, and shipping — nets the seller ~$8,800. If you paid $8,000 for the card, that\'s an 8% gross return before inflation and opportunity cost. High gross prices do not always mean high net returns.',
        calloutType: 'warning',
      },
      {
        heading: 'The grade calculus: when does upgrading make sense?',
        body: 'If you own a PSA 8 of an iconic card, should you sell it and buy the PSA 9? Or buy another PSA 8? The math is almost always against upgrading once you own a high-liquidity grade.',
        bullets: [
          'Upgrading from PSA 8 to PSA 9: typically requires paying 3–5× more for the card. The expected appreciation differential over time rarely justifies the upfront premium.',
          'Exception: PSA 10 on vintage. The PSA 10 population is genuinely tiny for most vintage cards — often 0–5 examples. The scarcity premium is real and durable.',
          'Diversification: owning three PSA 8 Jordan Fleers often outperforms owning one PSA 9, because you can sell one in a rally and hold the others.',
          'Holding a PSA 6 hoping for a run: legitimate strategy. Low-grade iconic cards are highly liquid and benefit from the same player demand as high-grade copies.',
        ],
      },
      {
        heading: 'The market cycles: what the data shows',
        body: 'The sports card market has gone through identifiable cycles. Understanding them helps you position correctly.',
        bullets: [
          '2019–2021: COVID-driven bubble. Stimulus checks + sports broadcast deals + social media attention = historic price spike. PSA 10 Jordan Fleer hit $738K. Griffey PSA 10 hit $22K.',
          '2021–2023: Correction phase. Most modern cards corrected 40–70% from peak. Vintage held better than modern.',
          '2023–2026: Stabilization. Market returned to fundamentals. Iconic vintage held value. Modern speculative rookies corrected sharply.',
          'Lesson: the floor for iconic vintage is supported by genuine scarcity and historical significance. The floor for modern speculative cards is determined by the next generation of collector interest — much less certain.',
        ],
        callout: 'Timing the market is not a consistent strategy. Being early on a player before a major milestone — and patient enough to hold through correction — has the best historical track record.',
        calloutType: 'info',
      },
      {
        heading: 'Practical portfolio principles',
        body: 'For collectors who want to treat their collection with investment discipline, these principles have held across market cycles.',
        bullets: [
          'Set a hard budget cap: never buy a card that requires borrowing or disrupts core financial obligations.',
          'Concentrate on iconic cards: own fewer, better cards rather than many speculative cards.',
          'Document everything: keep receipts, grade records, and photos for insurance and tax purposes.',
          'Tax awareness: in the US, sports card profits are generally taxable as capital gains or ordinary income depending on holding period and volume.',
          'Never fall in love with a card: the willingness to sell at a fair price is what separates collectors from investors.',
          'Use eBay sold comps before every purchase and every sale. Book value and sentiment are not the market.',
        ],
      },
    ],
  },
  {
    slug: 'pokemon-investing',
    title: 'Pokémon Card Investing: What Holds Value and What Does Not',
    summary: 'The Pokémon TCG market has produced extraordinary returns on specific cards — and catastrophic losses on others. This guide covers which Pokémon cards hold value across market cycles and how to think about the Pokémon market as a collector.',
    category: 'Pokémon',
    readTime: '11 min',
    icon: '⚡',
    gradient: 'from-yellow-900/40 via-amber-900/20 to-gray-900/40',
    featuredCards: [
      { slug: 'base1-4', type: 'pokemon', label: 'Base Set Charizard Holo', note: 'PSA 10: $511K at PWCC 2026' },
      { slug: 'base1-2', type: 'pokemon', label: 'Base Set Blastoise Holo', note: '1st Edition copies command top premiums' },
      { slug: 'base1-15', type: 'pokemon', label: 'Base Set Mewtwo Holo', note: 'Iconic character with strong demand' },
      { slug: 'sv8-236', type: 'pokemon', label: 'Prismatic Evolutions Umbreon ex SIR', note: 'Modern benchmark card' },
    ],
    content: [
      {
        heading: 'The Pokémon market is fundamentally different from sports cards',
        body: 'Pokémon cards are not tied to individual athlete performance. A LeBron James rookie card rises and falls with LeBron\'s career arc. A Base Set Charizard rises and falls with nostalgia for the original Pokémon generation, the health of the broader TCG market, and the ongoing success of the Pokémon franchise itself. This creates different risk and return profiles that most sports-crossover collectors underestimate.',
        bullets: [
          'Upside: Pokémon has no single-athlete career risk — Pikachu cannot retire or get injured.',
          'Downside: Pokémon card prices are partially driven by a 25–35 year old demographic\'s nostalgia premium, which may moderate over time.',
          'The franchise factor: Pokémon is The Pokémon Company\'s decision. New sets, new game mechanics, and new generations of Pokémon continually expand the collectible universe. This dilutes scarcity of older cards only marginally — the originals remain originals.',
        ],
      },
      {
        heading: 'The Vintage Tier: 1998–2003',
        body: 'The vintage Pokémon market is dominated by the original English-language sets from the Wizards of the Coast era (1998–2003): Base Set, Jungle, Fossil, Base Set 2, Team Rocket, Gym Heroes, Gym Challenge, Neo Genesis, Neo Discovery, Neo Revelation, Neo Destiny, Legendary Collection, and the early e-card sets. Among these, Base Set is by far the most important.',
        bullets: [
          'Base Set Shadowless Charizard PSA 10: the iconic benchmark. Sold for $511,100 at PWCC in 2026. Population is small — under 120 PSA 10 examples.',
          'Base Set Shadowless: distinguished by no shadow on the right side of the art box and right side of card. These are the earliest, rarest print variant.',
          '1st Edition Base Set: printed first, with the 1st Edition stamp. All have no shadow. Most valuable singles in the hobby.',
          'Unlimited Base Set: the most common print. Shadowless prints exist but are rarer than Unlimited.',
          'Key singles beyond Charizard: 1st Edition Blastoise, 1st Edition Venusaur, 1st Edition Mewtwo, and the full Shadowless Holo set.',
        ],
        callout: 'The 1st Edition stamp is on the left center of the card, below the art box. Counterfeit 1st Edition stamps exist. Buy only PSA-authenticated 1st Edition copies at meaningful price points.',
        calloutType: 'warning',
      },
      {
        heading: 'Grading vintage Pokémon: what holds premium',
        body: 'PSA grades hold the most liquidity and command the highest premiums in vintage Pokémon. BGS has growing acceptance for the highest-end vintage pieces. CGC Pokémon is still building collector trust.',
        bullets: [
          'PSA 10 Gem Mint: the benchmark. For Base Set Shadowless holos, PSA 10 is extraordinarily rare and commands enormous premium.',
          'PSA 9 Mint: the most commonly targeted grade for vintage investment. Achievable, liquid, and valuable.',
          'PSA 8 NM-MT: solid investment grade for vintage. High volume of sales provides reliable comps.',
          'PSA 7 and below: generally not investment-grade. Buy for the card, not the grade.',
          'Centering: Base Set cards were printed with consistent centering problems. Check left-right centering before grading submission.',
          'Surface scratches: the holo foil on Wizards-era holos is delicate. Any surface wear under UV light will affect grade.',
        ],
      },
      {
        heading: 'The Modern Era: 2017–present (Scarlet and Violet focus)',
        body: 'The modern era of Pokémon TCG runs from Sun and Moon (2017) through the current Scarlet and Violet series. These sets feature dramatically better print quality, more art card varieties, and significantly higher PSA 10 populations. The investment dynamics are fundamentally different from vintage.',
        bullets: [
          'Full Art Trainers: historically the highest-demand non-character cards. N, Lillie, Cynthia — the character-based Full Arts from previous eras.',
          'Special Illustration Rares (SIR): introduced in Scarlet and Violet, these are the modern-era flagship cards. Each set\'s SIR Pokémon ex are the collecting targets.',
          'Illustration Rares (IR): one step below SIR — beautiful art, more achievable price points.',
          'Eeveelution premium: Sylveon, Umbreon, Espeon, and Leafeon SIRs from Prismatic Evolutions (January 2026) are the current modern benchmark cards.',
          'PSA 10 population risk: modern cards are printed with much higher quality control. PSA 10 populations can reach 1,000+ on a popular SIR within a year of release, which caps the grade premium.',
        ],
        callout: 'The key risk in modern Pokémon: print runs are enormous and PSA 10 populations grow continuously. A card worth $400 as PSA 10 with a pop of 50 may be worth $150 a year later with a pop of 800. Track pop reports.',
        calloutType: 'warning',
      },
      {
        heading: 'Japanese cards: a separate market with real upside',
        body: 'Japanese Pokémon cards often predate their English counterparts by several months and sometimes contain alternate prints not available in English at all. The Japanese market has its own dynamics that English-focused collectors often overlook.',
        bullets: [
          'Promo cards: Japanese promo distributions (events, tournaments, lottery) produce extremely rare cards that never appear in English.',
          'Art Series: Japanese-exclusive alternate full-art prints that differ from English equivalents.',
          'Print quality: Japanese cards are generally considered to have superior print quality, which makes PSA 10 slightly more achievable.',
          'Market depth: the Japanese market is real but English resale is limited — authenticate Japanese rarity claims carefully.',
          'Trophy cards: competition trophy cards (Tropical Mega Battle, World Championship promos) are among the rarest Pokémon items in existence.',
        ],
        callout: 'Japanese Pokémon Illustrator (Pikachu trophy card) is widely considered the most valuable Pokémon card. One copy graded PSA 10 sold for $5.275 million. There are estimated 23–39 total copies in existence.',
        calloutType: 'info',
      },
      {
        heading: 'What does not hold value',
        body: 'Most Pokémon cards purchased at retail lose value. Understanding the bad trades is as important as understanding the good ones.',
        bullets: [
          'Common cards: 99%+ of cards pulled from any pack have zero secondary market value. Expect bulk value ($0.01–0.10 per card).',
          'Uncommon holos from modern sets: the non-featured holos in any set typically sell for $0.25–2.00 raw.',
          'Sealed product (most cases): while sealed booster boxes and ETBs have shown appreciation in vintage, modern sealed product is regularly reprinted, capping upside. Most modern sealed product will be worth less in 5 years than today when adjusted for inflation.',
          'Grading common modern cards: costs exceed realistic value add for any card below about $75 raw.',
          'Opening packs for investment: expected value of a retail booster pack is approximately 35–45 cents per dollar spent. Opening for fun is great; opening for profit is statistically negative.',
        ],
        callout: 'The classic mistake: buying a full booster box because "it might have the Charizard." The math does not work at retail. If you want the Charizard, buy the Charizard.',
        calloutType: 'warning',
      },
      {
        heading: 'Building a Pokémon collection that holds value',
        body: 'The Pokémon cards that have held or appreciated over 10+ year windows share common characteristics. Building around these principles gives you the best risk-adjusted position.',
        bullets: [
          'Focus on Iconic Pokémon: Charizard, Pikachu, Mewtwo, Umbreon, Gengar, Eevee. These hold collector demand across generations.',
          'First-of-kind cards: the first PSA 10 of a new Pokémon form, the first Secret Rare of a fan-favorite. Novelty plus demand.',
          'Complete vintage sets: a fully graded PSA 9 or 10 Shadowless or 1st Edition Base Set commands significant premium as a complete collection vs. individual singles.',
          'Trophy and promotional rarity: genuinely scarce promos that were never mass-produced have the best long-run appreciation because supply is truly fixed.',
          'Buy the best grade you can afford: a PSA 9 of an iconic card outperforms a PSA 10 of a generic card in virtually every historical data comparison.',
        ],
      },
    ],
  },
  {
    slug: 'most-valuable-sports-cards',
    title: 'The 50 Most Valuable Sports Cards of All Time',
    summary: 'Every record sale, every current range, and why each card commands its premium. Baseball, basketball, football, and hockey — ranked by verified auction record.',
    category: 'Market Data',
    readTime: '12 min',
    icon: '🏆',
    gradient: 'from-amber-900/40 via-yellow-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1909-t206-honus-wagner', type: 'sports', label: '1909 T206 Honus Wagner', note: 'Record: $7.25M' },
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'Record: $12.6M' },
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'Record: $738,000 PSA 10' },
      { slug: '1948-leaf-jackie-robinson-79', type: 'sports', label: '1948 Leaf Jackie Robinson #79', note: 'Historically significant RC' },
      { slug: '1966-67-topps-bobby-orr-35', type: 'sports', label: '1966-67 Topps Bobby Orr #35', note: 'Most valuable hockey RC' },
    ],
    content: [],
  },
  {
    slug: 'most-valuable-pokemon-cards',
    title: 'The 50 Most Valuable Pokémon Cards of All Time',
    summary: 'From the $5.275M Pikachu Illustrator to the most coveted modern alt arts. Record prices, current ranges, and what makes each card irreplaceable.',
    category: 'Market Data',
    readTime: '12 min',
    icon: '⚡',
    gradient: 'from-yellow-900/40 via-amber-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'card-market-2026',
    title: 'State of the Card Market: 2026 Analysis',
    summary: 'Fanatics overproduction backlash, PSA grading at 3.75M+ submissions, Pokémon TCG Pocket driving physical demand, vintage stability vs modern volatility. Deep dive.',
    category: 'Market Analysis',
    readTime: '15 min',
    icon: '📊',
    gradient: 'from-violet-900/40 via-indigo-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '2022-23-panini-prizm-victor-wembanyama-258', type: 'sports', label: '2022-23 Prizm Wembanyama #258', note: 'Hottest modern card' },
      { slug: '2024-panini-prizm-caitlin-clark-rc', type: 'sports', label: '2024 Prizm Caitlin Clark RC', note: 'Most searched card of 2024' },
      { slug: '2023-topps-chrome-corbin-carroll-rc-150', type: 'sports', label: '2023 Chrome Corbin Carroll RC', note: '2023 NL ROY' },
      { slug: '2023-panini-prizm-cj-stroud-rc-301', type: 'sports', label: '2023 Prizm C.J. Stroud RC', note: '2023 OROY' },
    ],
    content: [],
  },
  {
    slug: 'best-cards-under-10',
    title: '30 Best Sports Cards Under $10',
    summary: 'Build a Hall of Fame collection for the price of lunch. Junk wax era rookies, HOF commons, and vintage Pokémon — all under $10 in PSA 9. The smartest entry point into card collecting.',
    category: 'Buying Guide',
    readTime: '7 min',
    icon: '🪙',
    gradient: 'from-emerald-900/40 via-green-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'best-cards-under-25',
    title: '40 Best Sports Cards Under $25',
    summary: 'At $25 you unlock PSA-graded Hall of Famers and iconic rookies across every sport. The sweet spot for serious collectors on a budget — real slabs, real legends, real value.',
    category: 'Buying Guide',
    readTime: '9 min',
    icon: '💵',
    gradient: 'from-teal-900/40 via-cyan-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'best-cards-under-50',
    title: '40 Best Sports Cards Under $50',
    summary: 'The collector\'s sweet spot. Graded rookies of Kobe, Griffey, Curry, and Crosby — genuine blue chips at prices that won\'t break the bank. Where smart money enters the hobby.',
    category: 'Buying Guide',
    readTime: '9 min',
    icon: '💎',
    gradient: 'from-violet-900/40 via-purple-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'best-cards-under-100',
    title: '50 Best Sports Cards Under $100',
    summary: 'Hall of Famers, iconic rookies, and vintage classics you can actually afford. PSA 9 prices, why each card matters, and exactly what to look for when buying. The largest audience in the hobby — not everyone collects $100K cards.',
    category: 'Buying Guide',
    readTime: '10 min',
    icon: '💰',
    gradient: 'from-emerald-900/40 via-teal-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1990-topps-frank-thomas-414', type: 'sports', label: '1990 Topps Frank Thomas #414', note: 'HOF RC under $20 raw' },
      { slug: '1985-topps-mark-mcgwire-401', type: 'sports', label: '1985 Topps Mark McGwire #401', note: 'Team USA RC under $30' },
      { slug: '1990-91-score-martin-brodeur-439', type: 'sports', label: '1990-91 Score Martin Brodeur #439', note: 'Winningest goalie ever — under $30' },
      { slug: '1989-score-barry-sanders-257', type: 'sports', label: '1989 Score Barry Sanders #257', note: 'HOF RC under $100 PSA 8' },
    ],
    content: [],
  },
  {
    slug: 'best-pokemon-investments',
    title: 'Best Pokémon Card Investments for 2026',
    summary: 'Vintage graded, sealed product, modern alt arts, and raw submission plays — analyzed by risk tier, entry price, and long-term thesis. No hype, no speculation dressed as analysis.',
    category: 'Investing',
    readTime: '12 min',
    icon: '⚡',
    gradient: 'from-yellow-900/40 via-amber-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'fake-cards',
    title: 'How to Spot Fake Sports Cards and Pokémon Cards',
    summary: 'Trimmed cards, fake PSA slabs, recolored vintage, forged autographs, and counterfeit Pokémon — every major fraud type with specific detection methods, tools, and red flags.',
    category: 'Authentication',
    readTime: '9 min',
    icon: '🔍',
    gradient: 'from-rose-900/40 via-red-900/20 to-gray-900/40',
    featuredCards: [
      { slug: '1909-t206-honus-wagner', type: 'sports', label: '1909 T206 Honus Wagner', note: 'Most counterfeited card in history' },
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'Common trimming and counterfeit target' },
      { slug: '1952-topps-mickey-mantle-311', type: 'sports', label: '1952 Topps Mickey Mantle #311', note: 'Frequent trimming victim' },
    ],
    content: [],
  },
  {
    slug: 'psa-vs-bgs-vs-cgc',
    title: 'PSA vs BGS vs CGC: Which Grading Company Should You Use?',
    summary: 'Complete comparison of the three major card grading services. Costs, turnaround times, resale premiums, label types, and a decision framework for which grader fits your cards.',
    category: 'Grading',
    readTime: '10 min',
    icon: '🏅',
    gradient: 'from-red-900/30 via-blue-900/20 to-amber-900/30',
    featuredCards: [
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'PSA 10 commands highest premium' },
      { slug: '2022-23-panini-prizm-victor-wembanyama-258', type: 'sports', label: '2022-23 Prizm Wembanyama #258', note: 'Modern card — all 3 graders viable' },
    ],
    content: [],
  },
  {
    slug: 'tcgplayer-vs-ebay',
    title: 'TCGPlayer vs eBay: Where to Buy and Sell Cards',
    summary: 'Honest comparison of the two biggest card marketplaces. Fees, buyer protection, pricing transparency, and which platform is better for buying vs selling, raw vs graded.',
    category: 'Buying Guide',
    readTime: '8 min',
    icon: '🛒',
    gradient: 'from-emerald-900/30 via-blue-900/20 to-gray-900/30',
    featuredCards: [
      { slug: '2018-topps-chrome-shohei-ohtani-150', type: 'sports', label: '2018 Topps Chrome Ohtani #150', note: 'Active on both platforms' },
    ],
    content: [],
  },
  {
    slug: 'how-to-sell-cards',
    title: 'How to Sell Sports Cards: The Complete Guide',
    summary: 'Step-by-step guide to selling sports cards and Pokemon cards. Where to sell, how to price, shipping tips, platform fees, and how to maximize your return.',
    category: 'Selling',
    readTime: '12 min',
    icon: '💵',
    gradient: 'from-emerald-900/30 via-green-900/20 to-gray-900/30',
    featuredCards: [
      { slug: '1986-87-fleer-michael-jordan-57', type: 'sports', label: '1986-87 Fleer Michael Jordan #57', note: 'High-value card — auction house territory' },
      { slug: '2000-playoff-contenders-tom-brady-144', type: 'sports', label: '2000 Playoff Contenders Tom Brady #144', note: 'eBay auction for max exposure' },
    ],
    content: [],
  },
  {
    slug: 'best-rookie-cards-2026',
    title: 'Best Rookie Cards to Invest In: 2026 Picks',
    summary: 'Expert picks for the best rookie cards to buy across baseball, basketball, football, and hockey. Risk tiers, entry prices, and investment thesis for each player.',
    category: 'Investing',
    readTime: '10 min',
    icon: '📈',
    gradient: 'from-amber-900/30 via-yellow-900/20 to-gray-900/30',
    featuredCards: [
      { slug: '2022-23-panini-prizm-victor-wembanyama-258', type: 'sports', label: '2023-24 Prizm Wembanyama #258', note: '#1 pick — Low Risk' },
      { slug: '2023-topps-chrome-corbin-carroll-rc-150', type: 'sports', label: '2023 Chrome Corbin Carroll RC', note: 'NL ROY — Low Risk' },
      { slug: '2024-panini-prizm-caitlin-clark-rc', type: 'sports', label: '2024 Prizm Caitlin Clark RC', note: 'Most searched card — High Risk' },
    ],
    content: [],
  },
  {
    slug: 'psa-grading-scale',
    title: 'PSA Grading Scale Explained: What is PSA 10?',
    summary: 'Complete PSA grading scale from PSA 1 to PSA 10 Gem Mint. What each grade means, centering requirements, the four factors PSA evaluates, and PSA 9 vs PSA 10 price differences.',
    category: 'Grading',
    readTime: '8 min',
    icon: '🔢',
    gradient: 'from-yellow-900/40 via-amber-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'card-storage-guide',
    title: 'How to Store and Protect Your Card Collection',
    summary: 'Penny sleeves, top loaders, one-touch holders, binder pages, and climate control. Every storage method compared, with the right solution for every budget and card value.',
    category: 'Beginner',
    readTime: '7 min',
    icon: '📦',
    gradient: 'from-emerald-900/40 via-teal-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'card-collecting-glossary',
    title: 'Card Collecting Glossary: 80+ Terms Explained',
    summary: 'Every term you need to know: RC, refractor, auto, hit, junk wax, wax, hobby vs retail, parallels, short prints, slabs, comps, and more.',
    category: 'Beginner',
    readTime: '10 min',
    icon: '📖',
    gradient: 'from-blue-900/40 via-indigo-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'best-boxes-2025',
    title: 'Best Sports Card Boxes to Buy in 2025',
    summary: 'The 12 best sports card boxes to buy in 2025 across hobby, retail, and value tiers. Prices, hit rates, key cards to chase, and honest verdicts for baseball, basketball, football, and hockey.',
    category: 'Buying',
    readTime: '9 min',
    icon: '\ud83d\udce6',
    gradient: 'from-amber-900/40 via-orange-900/20 to-gray-900/40',
    content: [],
  },
  {
    slug: 'budget-collecting',
    title: 'How to Build a Card Collection on a Budget',
    summary: 'Smart strategies at every price point: $25, $50-$100, and $200+/month. Where to find deals, what to buy, and the #1 rule that saves budget collectors money.',
    category: 'Beginner',
    readTime: '8 min',
    icon: '💰',
    gradient: 'from-green-900/40 via-emerald-900/20 to-gray-900/40',
    content: [],
  },
];

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find(g => g.slug === slug);
}
